'use client';
import {useEffect,useMemo,useState} from 'react';

const euro=(v:any)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(v||0));
const day=()=>new Date().toISOString().slice(0,10);
const blank:any={contact:{customer_id:'',first_name:'',last_name:'',role:'',email:'',phone:'',mobile:'',is_primary:0,notes:''},note:{customer_id:'',contact_id:'',title:'',content:''},task:{customer_id:'',contact_id:'',title:'',description:'',due_date:day(),priority:'normaal',status:'open',assigned_to:''},activity:{customer_id:'',contact_id:'',activity_type:'telefoon',subject:'',description:'',activity_at:new Date().toISOString().slice(0,16)},file:{customer_id:'',contact_id:'',file_name:'',file_url:'',mime_type:'',description:''}};
type Tab='klanten'|'contacten'|'taken'|'tijdlijn'|'bestanden';

export default function CRM(){
 const [data,setData]=useState<any>({customers:[],contacts:[],notes:[],tasks:[],activities:[],files:[],kpis:{}}),[tab,setTab]=useState<Tab>('klanten'),[query,setQuery]=useState(''),[form,setForm]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState<any>(null);
 async function load(){setLoading(true);const r=await fetch('/api/crm',{cache:'no-store'}),j=await r.json();setLoading(false);if(!r.ok)setError(j.error||'Laden mislukt');else{setData(j);setError('')}}
 useEffect(()=>{load()},[]);
 async function send(body:any,method='POST'){const r=await fetch('/api/crm',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok){setError(j.error||'Actie mislukt');return false}setError('');await load();return true}
 async function save(){if(await send({action:form.kind,data:form.data}))setForm(null)}
 async function done(x:any){await send({action:'task',data:{id:x.id,status:x.status==='gereed'?'open':'gereed'}},'PUT')}
 const source:any=tab==='klanten'?data.customers:tab==='contacten'?data.contacts:tab==='taken'?data.tasks:tab==='tijdlijn'?[...data.activities,...data.notes.map((x:any)=>({...x,activity_at:x.created_at,activity_type:'notitie',subject:x.title||'Notitie',description:x.content}))]:data.files;
 const rows=useMemo(()=>source.filter((x:any)=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[source,query]);
 function open(kind:string,customer?:any){setForm({kind,data:{...blank[kind],customer_id:customer?.id||selected?.id||''}})}
 const customerContacts=(id:number)=>data.contacts.filter((x:any)=>Number(x.customer_id)===Number(id));
 return <main><header><div><small>KlusHulp Noord ERP v8.1</small><h1>CRM Pro</h1><p>Klanten, contactpersonen, taken, notities, bestanden en omzetanalyse.</p></div><div className="actions"><a href="/">Administratie</a><button onClick={()=>open(tab==='contacten'?'contact':tab==='taken'?'task':tab==='tijdlijn'?'activity':tab==='bestanden'?'file':'note')}>+ Nieuw</button></div></header>
 {error&&<div className="error">{error}</div>}
 <section className="stats"><Stat n={data.kpis.customers||0} l="Klanten"/><Stat n={data.kpis.prospects||0} l="Prospects"/><Stat n={data.kpis.openTasks||0} l="Open taken"/><Stat n={data.kpis.overdueTasks||0} l="Te laat"/><Stat n={euro(data.kpis.revenue)} l="Omzet"/><Stat n={euro(data.kpis.outstanding)} l="Openstaand"/></section>
 <nav>{(['klanten','contacten','taken','tijdlijn','bestanden'] as Tab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>
 <input className="search" placeholder="Zoeken in CRM..." value={query} onChange={e=>setQuery(e.target.value)}/>
 <section className="card">{loading?<p>Laden...</p>:tab==='klanten'?<div className="grid">{rows.map((c:any)=><article key={c.id} onClick={()=>setSelected(c)}><div className="title"><h3>{c.company_name||c.name}</h3><span>{c.status||'actief'}</span></div><p>{c.email||'Geen e-mail'}<br/>{c.phone||c.mobile||'Geen telefoon'}<br/>{c.city||'Geen plaats'}</p><div className="mini"><b>{euro(c.revenue)}</b><span>{c.contact_count||0} contacten</span><span>{c.open_task_count||0} taken</span></div><button onClick={e=>{e.stopPropagation();setSelected(c)}}>Open dossier</button></article>)}</div>:<div className="table"><div className="tr head"><span>Onderwerp</span><span>Klant</span><span>Details</span><span>Datum/status</span><span>Actie</span></div>{rows.map((x:any)=><div className="tr" key={`${tab}-${x.id}`}><span><b>{x.first_name?`${x.first_name} ${x.last_name||''}`:x.title||x.subject||x.file_name}</b><small>{x.role||x.activity_type||x.priority||''}</small></span><span>{x.customer_name||'-'}</span><span>{x.email||x.description||x.content||x.file_url||'-'}</span><span>{x.due_date||String(x.activity_at||x.created_at||'').slice(0,16)||x.status}</span><span>{tab==='taken'?<button onClick={()=>done(x)}>{x.status==='gereed'?'Heropen':'Gereed'}</button>:tab==='bestanden'?<a href={x.file_url} target="_blank">Open</a>:'-'}</span></div>)}</div>}</section>
 {selected&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><aside className="drawer"><div className="title"><div><small>Klantdossier</small><h2>{selected.company_name||selected.name}</h2></div><button onClick={()=>setSelected(null)}>Sluiten</button></div><div className="detail"><Stat n={euro(selected.revenue)} l="Omzet"/><Stat n={euro(selected.outstanding)} l="Openstaand"/><Stat n={selected.document_count||0} l="Documenten"/></div><section><h3>Contactpersonen</h3>{customerContacts(selected.id).map((x:any)=><p key={x.id}><b>{x.first_name} {x.last_name}</b> {x.is_primary?'⭐':''}<br/>{x.role||''} · {x.email||''} · {x.mobile||x.phone||''}</p>)}<button onClick={()=>open('contact',selected)}>+ Contactpersoon</button></section><section><h3>Snelle acties</h3><div className="actions"><button onClick={()=>open('note',selected)}>Notitie</button><button onClick={()=>open('task',selected)}>Taak</button><button onClick={()=>open('activity',selected)}>Contactmoment</button><button onClick={()=>open('file',selected)}>Bestand</button></div></section><section><h3>Tijdlijn</h3>{data.activities.filter((x:any)=>Number(x.customer_id)===Number(selected.id)).slice(0,20).map((x:any)=><div className="timeline" key={x.id}><b>{x.subject}</b><small>{x.activity_type} · {new Date(x.activity_at).toLocaleString('nl-NL')}</small><p>{x.description}</p></div>)}</section></aside></div>}
 {form&&<div className="overlay"><div className="modal"><h2>Nieuw {form.kind}</h2><Form kind={form.kind} data={form.data} set={(v:any)=>setForm({...form,data:v})} customers={data.customers} contacts={data.contacts}/><div className="actions"><button onClick={()=>setForm(null)}>Annuleren</button><button onClick={save}>Opslaan</button></div></div></div>}
 <style jsx>{`main{padding:28px;display:grid;gap:18px;max-width:1600px;margin:auto}header,.title,.actions,nav{display:flex;align-items:center;justify-content:space-between;gap:10px}header h1{margin:4px 0}a,button{font:inherit;border:0;border-radius:9px;padding:10px 14px;background:#111827;color:#fff;text-decoration:none;cursor:pointer}.stats{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.stat,.card,.drawer section{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:16px}.stat{display:grid}.stat b{font-size:21px}.stat span,small{color:#64748b}nav{justify-content:flex-start}nav button{background:#e5e7eb;color:#111827;text-transform:capitalize}nav .active{background:#111827;color:#fff}.search,input,select,textarea{font:inherit;border:1px solid #cbd5e1;border-radius:9px;padding:10px;width:100%}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.grid article{border:1px solid #e5e7eb;border-radius:12px;padding:15px;cursor:pointer}.mini{display:flex;gap:12px;flex-wrap:wrap;margin:12px 0}.table{display:grid}.tr{display:grid;grid-template-columns:1.2fr 1fr 2fr 1fr .7fr;gap:12px;padding:12px;border-bottom:1px solid #eee;align-items:center}.tr span{overflow-wrap:anywhere}.head{font-weight:700}.error{background:#fee2e2;padding:12px;border-radius:10px}.overlay{position:fixed;inset:0;background:#0008;z-index:50;display:flex;justify-content:flex-end}.drawer{width:min(760px,100%);height:100%;overflow:auto;background:#f8fafc;padding:20px}.drawer section{margin-top:14px}.detail{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.timeline{border-left:3px solid #111827;padding-left:12px;margin:14px 0}.modal{background:#fff;border-radius:16px;padding:22px;max-width:800px;width:100%;margin:auto;max-height:90vh;overflow:auto}.form{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:16px 0}.form label{display:grid;gap:6px}.full{grid-column:1/-1}@media(max-width:1000px){.stats{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:1fr 1fr}.tr{grid-template-columns:1fr 1fr}.head{display:none}}@media(max-width:650px){main{padding:14px}.stats,.grid,.detail,.form{grid-template-columns:1fr}header{align-items:flex-start;flex-direction:column}.full{grid-column:auto}}`}</style>
 </main>
}
function Stat({n,l}:{n:any,l:string}){return <article className="stat"><b>{n}</b><span>{l}</span></article>}
function Form({kind,data,set,customers,contacts}:any){const field=(k:string,l:string,type='text')=><label>{l}<input type={type} value={data[k]??''} onChange={e=>set({...data,[k]:type==='checkbox'?e.target.checked?1:0:e.target.value})}/></label>;const selectCustomer=<label>Klant<select value={data.customer_id||''} onChange={e=>set({...data,customer_id:e.target.value,contact_id:''})}><option value="">Selecteer klant</option>{customers.map((x:any)=><option key={x.id} value={x.id}>{x.company_name||x.name}</option>)}</select></label>;const selectContact=<label>Contactpersoon<select value={data.contact_id||''} onChange={e=>set({...data,contact_id:e.target.value})}><option value="">Geen</option>{contacts.filter((x:any)=>!data.customer_id||Number(x.customer_id)===Number(data.customer_id)).map((x:any)=><option key={x.id} value={x.id}>{x.first_name} {x.last_name}</option>)}</select></label>;return <div className="form">{selectCustomer}{kind!=='contact'&&selectContact}{kind==='contact'&&<>{field('first_name','Voornaam')}{field('last_name','Achternaam')}{field('role','Functie')}{field('email','E-mail','email')}{field('phone','Telefoon')}{field('mobile','Mobiel')}{field('is_primary','Primair contact','checkbox')}<label className="full">Notities<textarea value={data.notes} onChange={e=>set({...data,notes:e.target.value})}/></label></>}{kind==='note'&&<>{field('title','Titel')}<label className="full">Notitie<textarea value={data.content} onChange={e=>set({...data,content:e.target.value})}/></label></>}{kind==='task'&&<>{field('title','Taak')}{field('due_date','Deadline','date')}<label>Prioriteit<select value={data.priority} onChange={e=>set({...data,priority:e.target.value})}><option>laag</option><option>normaal</option><option>hoog</option><option>spoed</option></select></label>{field('assigned_to','Toegewezen aan')}<label className="full">Omschrijving<textarea value={data.description} onChange={e=>set({...data,description:e.target.value})}/></label></>}{kind==='activity'&&<>{field('subject','Onderwerp')}<label>Type<select value={data.activity_type} onChange={e=>set({...data,activity_type:e.target.value})}><option>telefoon</option><option>email</option><option>whatsapp</option><option>bezoek</option><option>overig</option></select></label>{field('activity_at','Datum en tijd','datetime-local')}<label className="full">Beschrijving<textarea value={data.description} onChange={e=>set({...data,description:e.target.value})}/></label></>}{kind==='file'&&<>{field('file_name','Bestandsnaam')}{field('file_url','Bestands-URL','url')}{field('mime_type','Bestandstype')}<label className="full">Beschrijving<textarea value={data.description} onChange={e=>set({...data,description:e.target.value})}/></label></>}</div>}
