'use client';
import {useEffect,useState} from 'react';

const fields=[
 ['legal_name','Juridische naam'],['trade_name','Handelsnaam'],['owner_name','Naam eigenaar'],['street','Straat'],['house_number','Huisnummer'],['postal_code','Postcode'],['city','Plaats'],['country','Land'],['email','Zakelijk e-mailadres'],['phone','Telefoonnummer'],['website','Website'],['kvk_number','KVK-nummer'],['vat_id','Btw-identificatienummer'],['iban','IBAN'],['bic','BIC'],['payment_term_days','Betaaltermijn in dagen'],['quote_valid_days','Geldigheid offerte in dagen'],['invoice_prefix','Voorloop factuurnummer'],['quote_prefix','Voorloop offertenummer'],['default_vat_rate','Standaard btw-percentage']
];
export default function InstellingenPage(){
 const [form,setForm]=useState<any>({}),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch('/api/instellingen',{cache:'no-store'}).then(r=>r.json()).then(j=>{setForm(j);setLoading(false)})},[]);
 async function save(){setMessage('Opslaan…');const r=await fetch('/api/instellingen',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();setMessage(r.ok?'Bedrijfsgegevens opgeslagen':j.error||'Opslaan mislukt')}
 if(loading)return <main className="settings"><p>Laden…</p></main>;
 return <main className="settings"><header><div><small>Eenmanszaak</small><h1>Bedrijfsinstellingen</h1><p>Deze gegevens worden gebruikt op offertes, facturen en andere zakelijke documenten.</p></div><button onClick={save}>Opslaan</button></header>{message&&<div className="notice">{message}</div>}<section className="card"><h2>Bedrijfs- en belastinggegevens</h2><div className="grid">{fields.map(([key,label])=><label key={key}>{label}<input type={['payment_term_days','quote_valid_days','default_vat_rate'].includes(key)?'number':'text'} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div></section><section className="card"><h2>Documentteksten</h2><label>Voettekst op offertes en facturen<textarea rows={4} value={form.footer_text||''} onChange={e=>setForm({...form,footer_text:e.target.value})}/></label><label>Algemene voorwaarden / betaalafspraken<textarea rows={7} value={form.terms_text||''} onChange={e=>setForm({...form,terms_text:e.target.value})}/></label></section><section className="card checklist"><h2>Controle voor correcte facturen</h2><p>Vul minimaal juridische naam, vestigingsadres, KVK-nummer, btw-identificatienummer, factuurnummering, factuurdatum, leverdatum, klantgegevens, omschrijving, bedrag exclusief btw, btw-tarief en btw-bedrag in.</p></section><style jsx>{`.settings{max-width:1250px;margin:auto;padding:28px;color:#17211e}.settings header{display:flex;justify-content:space-between;gap:18px;align-items:center;margin-bottom:18px}.settings h1{margin:4px 0;font-size:34px}.settings p,.settings small{color:#667085}.settings button{border:0;border-radius:10px;background:#173f35;color:#fff;padding:11px 18px;font-weight:800;cursor:pointer}.card{background:#fff;border:1px solid #e1e7e4;border-radius:17px;padding:20px;margin:14px 0;box-shadow:0 8px 24px #102f280a}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}label{display:grid;gap:6px;font-weight:700;font-size:13px}input,textarea{width:100%;box-sizing:border-box;border:1px solid #cad5d1;border-radius:10px;padding:11px;font:inherit}.notice{background:#ecfdf3;border:1px solid #86efac;border-radius:12px;padding:12px}.checklist{border-left:5px solid #f5c400}@media(max-width:900px){.grid{grid-template-columns:1fr}.settings header{align-items:flex-start;flex-direction:column}}`}</style></main>}
