'use client';
import {useEffect,useMemo,useState} from 'react';

type Vehicle={id:number;registration:string;brand:string;model:string;vehicle_type:string;year?:number;fuel_type?:string;current_mileage:number;assigned_to?:string;status:string;apk_expiry?:string;insurance_expiry?:string;total_cost:number;business_km:number;private_km:number;apk_days?:number};
const money=(n:any)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(n||0));
const date=(v:any)=>v?String(v).slice(0,10):'-';

export default function VoertuigenPage(){
 const [data,setData]=useState<any>({vehicles:[],alerts:[],kpis:{}}),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const [vehicle,setVehicle]=useState<any>({registration:'',brand:'',model:'',vehicle_type:'bestelbus',status:'actief',current_mileage:0});
 const [trip,setTrip]=useState<any>({trip_date:new Date().toISOString().slice(0,10),start_mileage:0,end_mileage:0,private_km:0});
 const [cost,setCost]=useState<any>({cost_date:new Date().toISOString().slice(0,10),cost_type:'brandstof',amount_ex_vat:0,vat_amount:0});
 const [maintenance,setMaintenance]=useState<any>({maintenance_type:'Onderhoudsbeurt',status:'gepland'});
 async function load(){setLoading(true);const r=await fetch('/api/voertuigen');const j=await r.json();setData(j);setLoading(false)}
 async function open(id:number){const r=await fetch('/api/voertuigen?id='+id);setSelected(await r.json())}
 useEffect(()=>{load()},[]);
 async function post(action:string,payload:any){setMessage('');const r=await fetch('/api/voertuigen',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data:payload})});const j=await r.json();if(!r.ok){setMessage(j.error||'Opslaan mislukt');return false}setMessage('Opgeslagen');await load();return true}
 const alerts=useMemo(()=>data.alerts||[],[data]);
 return <main className="p-4 md:p-8 space-y-6">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold">Bedrijfswagens Pro</h1><p className="text-slate-600">Wagenpark, ritten, kosten, APK en onderhoud.</p></div><button className="rounded-xl bg-slate-900 px-4 py-2 text-white" onClick={()=>setSelected(null)}>Overzicht</button></div>
  {message&&<div className="rounded-xl border p-3 bg-white">{message}</div>}
  <section className="grid grid-cols-2 lg:grid-cols-4 gap-3">
   {[['Actieve voertuigen',data.kpis?.active||0],['Zakelijke kilometers',Number(data.kpis?.businessKm||0).toLocaleString('nl-NL')],['Totale kosten',money(data.kpis?.totalCosts)],['APK binnen 60 dagen',data.kpis?.apkSoon||0]].map(([a,b])=><div key={String(a)} className="rounded-2xl border bg-white p-4"><div className="text-sm text-slate-500">{a}</div><div className="text-2xl font-bold mt-1">{b}</div></div>)}
  </section>
  {alerts.length>0&&<section className="rounded-2xl border border-amber-300 bg-amber-50 p-4"><h2 className="font-bold mb-2">Aandacht nodig</h2>{alerts.map((a:any)=><div key={a.id} className="text-sm">{a.registration} · {a.brand} {a.model} · APK {date(a.apk_expiry)} · verzekering {date(a.insurance_expiry)}</div>)}</section>}
  {!selected?<>
   <section className="rounded-2xl border bg-white p-4"><h2 className="text-xl font-bold mb-4">Voertuig toevoegen</h2><div className="grid md:grid-cols-4 gap-3">
    <input className="border rounded-lg p-2" placeholder="Kenteken" value={vehicle.registration} onChange={e=>setVehicle({...vehicle,registration:e.target.value})}/><input className="border rounded-lg p-2" placeholder="Merk" value={vehicle.brand} onChange={e=>setVehicle({...vehicle,brand:e.target.value})}/><input className="border rounded-lg p-2" placeholder="Model" value={vehicle.model} onChange={e=>setVehicle({...vehicle,model:e.target.value})}/><select className="border rounded-lg p-2" value={vehicle.vehicle_type} onChange={e=>setVehicle({...vehicle,vehicle_type:e.target.value})}><option>bestelbus</option><option>personenauto</option><option>aanhanger</option><option>vrachtwagen</option></select>
    <input className="border rounded-lg p-2" type="number" placeholder="Bouwjaar" onChange={e=>setVehicle({...vehicle,year:e.target.value})}/><input className="border rounded-lg p-2" placeholder="Brandstof" onChange={e=>setVehicle({...vehicle,fuel_type:e.target.value})}/><input className="border rounded-lg p-2" type="number" placeholder="Kilometerstand" value={vehicle.current_mileage} onChange={e=>setVehicle({...vehicle,current_mileage:e.target.value})}/><input className="border rounded-lg p-2" placeholder="Toegewezen aan" onChange={e=>setVehicle({...vehicle,assigned_to:e.target.value})}/>
    <label className="text-sm">APK vervaldatum<input className="border rounded-lg p-2 w-full" type="date" onChange={e=>setVehicle({...vehicle,apk_expiry:e.target.value})}/></label><label className="text-sm">Verzekering vervalt<input className="border rounded-lg p-2 w-full" type="date" onChange={e=>setVehicle({...vehicle,insurance_expiry:e.target.value})}/></label><input className="border rounded-lg p-2" type="number" placeholder="Lease per maand" onChange={e=>setVehicle({...vehicle,lease_monthly:e.target.value})}/><button className="rounded-lg bg-emerald-600 text-white p-2 self-end" onClick={async()=>{if(await post('vehicle',vehicle))setVehicle({registration:'',brand:'',model:'',vehicle_type:'bestelbus',status:'actief',current_mileage:0})}}>Toevoegen</button>
   </div></section>
   <section className="rounded-2xl border bg-white overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-slate-50 text-left"><th className="p-3">Kenteken</th><th>Voertuig</th><th>Bestuurder</th><th>Km-stand</th><th>APK</th><th>Kosten</th><th>Status</th></tr></thead><tbody>{loading?<tr><td className="p-4" colSpan={7}>Laden...</td></tr>:(data.vehicles||[]).map((v:Vehicle)=><tr key={v.id} className="border-t hover:bg-slate-50 cursor-pointer" onClick={()=>open(v.id)}><td className="p-3 font-bold">{v.registration}</td><td>{v.brand} {v.model}</td><td>{v.assigned_to||'-'}</td><td>{Number(v.current_mileage||0).toLocaleString('nl-NL')}</td><td>{date(v.apk_expiry)}</td><td>{money(v.total_cost)}</td><td>{v.status}</td></tr>)}</tbody></table></section>
  </>:<VehicleDetail selected={selected} trip={trip} setTrip={setTrip} cost={cost} setCost={setCost} maintenance={maintenance} setMaintenance={setMaintenance} post={post} refresh={()=>open(selected.vehicle.id)}/>} 
 </main>
}

function VehicleDetail({selected,trip,setTrip,cost,setCost,maintenance,setMaintenance,post,refresh}:any){const v=selected.vehicle;if(!v)return <div>Voertuig niet gevonden.</div>;const save=async(action:string,d:any)=>{if(await post(action,{...d,vehicle_id:v.id})){await refresh()}};return <div className="space-y-5">
 <section className="rounded-2xl border bg-white p-5"><h2 className="text-2xl font-bold">{v.registration} · {v.brand} {v.model}</h2><div className="grid md:grid-cols-4 gap-3 mt-4 text-sm"><div><b>Kilometerstand</b><br/>{Number(v.current_mileage).toLocaleString('nl-NL')}</div><div><b>Bestuurder</b><br/>{v.assigned_to||'-'}</div><div><b>APK</b><br/>{date(v.apk_expiry)}</div><div><b>Totale kosten</b><br/>{money(v.total_cost)}</div></div></section>
 <div className="grid lg:grid-cols-3 gap-4">
  <section className="rounded-2xl border bg-white p-4 space-y-2"><h3 className="font-bold">Rit registreren</h3><input className="border rounded p-2 w-full" type="date" value={trip.trip_date} onChange={e=>setTrip({...trip,trip_date:e.target.value})}/><input className="border rounded p-2 w-full" placeholder="Bestuurder" onChange={e=>setTrip({...trip,driver:e.target.value})}/><div className="grid grid-cols-2 gap-2"><input className="border rounded p-2" type="number" placeholder="Beginstand" onChange={e=>setTrip({...trip,start_mileage:e.target.value})}/><input className="border rounded p-2" type="number" placeholder="Eindstand" onChange={e=>setTrip({...trip,end_mileage:e.target.value})}/></div><input className="border rounded p-2 w-full" type="number" placeholder="Privé km" onChange={e=>setTrip({...trip,private_km:e.target.value})}/><input className="border rounded p-2 w-full" placeholder="Van" onChange={e=>setTrip({...trip,from_location:e.target.value})}/><input className="border rounded p-2 w-full" placeholder="Naar" onChange={e=>setTrip({...trip,to_location:e.target.value})}/><input className="border rounded p-2 w-full" placeholder="Doel van de rit" onChange={e=>setTrip({...trip,purpose:e.target.value})}/><button className="bg-slate-900 text-white rounded p-2 w-full" onClick={()=>save('mileage',trip)}>Rit opslaan</button></section>
  <section className="rounded-2xl border bg-white p-4 space-y-2"><h3 className="font-bold">Kosten registreren</h3><input className="border rounded p-2 w-full" type="date" value={cost.cost_date} onChange={e=>setCost({...cost,cost_date:e.target.value})}/><select className="border rounded p-2 w-full" value={cost.cost_type} onChange={e=>setCost({...cost,cost_type:e.target.value})}><option>brandstof</option><option>onderhoud</option><option>reparatie</option><option>verzekering</option><option>wegenbelasting</option><option>lease</option><option>parkeren</option><option>overig</option></select><input className="border rounded p-2 w-full" placeholder="Omschrijving" onChange={e=>setCost({...cost,description:e.target.value})}/><input className="border rounded p-2 w-full" type="number" step="0.01" placeholder="Bedrag excl. BTW" onChange={e=>setCost({...cost,amount_ex_vat:e.target.value})}/><input className="border rounded p-2 w-full" type="number" step="0.01" placeholder="BTW" onChange={e=>setCost({...cost,vat_amount:e.target.value})}/><input className="border rounded p-2 w-full" placeholder="Leverancier" onChange={e=>setCost({...cost,supplier:e.target.value})}/><button className="bg-slate-900 text-white rounded p-2 w-full" onClick={()=>save('cost',cost)}>Kosten opslaan</button></section>
  <section className="rounded-2xl border bg-white p-4 space-y-2"><h3 className="font-bold">Onderhoud plannen</h3><input className="border rounded p-2 w-full" placeholder="Type onderhoud" value={maintenance.maintenance_type} onChange={e=>setMaintenance({...maintenance,maintenance_type:e.target.value})}/><textarea className="border rounded p-2 w-full" placeholder="Omschrijving" onChange={e=>setMaintenance({...maintenance,description:e.target.value})}/><input className="border rounded p-2 w-full" type="date" onChange={e=>setMaintenance({...maintenance,planned_date:e.target.value})}/><input className="border rounded p-2 w-full" type="number" placeholder="Bij kilometerstand" onChange={e=>setMaintenance({...maintenance,planned_mileage:e.target.value})}/><input className="border rounded p-2 w-full" placeholder="Garage/leverancier" onChange={e=>setMaintenance({...maintenance,supplier:e.target.value})}/><button className="bg-slate-900 text-white rounded p-2 w-full" onClick={()=>save('maintenance',maintenance)}>Onderhoud plannen</button></section>
 </div>
 <section className="rounded-2xl border bg-white p-4 overflow-x-auto"><h3 className="font-bold mb-3">Rittenhistorie</h3><table className="w-full text-sm"><thead><tr className="text-left"><th>Datum</th><th>Bestuurder</th><th>Route</th><th>Zakelijk</th><th>Privé</th><th>Eindstand</th></tr></thead><tbody>{selected.mileage.map((x:any)=><tr key={x.id} className="border-t"><td className="py-2">{date(x.trip_date)}</td><td>{x.driver||'-'}</td><td>{x.from_location||'-'} → {x.to_location||'-'}</td><td>{x.business_km} km</td><td>{x.private_km} km</td><td>{x.end_mileage}</td></tr>)}</tbody></table></section>
 <section className="rounded-2xl border bg-white p-4 overflow-x-auto"><h3 className="font-bold mb-3">Kostenhistorie</h3><table className="w-full text-sm"><thead><tr className="text-left"><th>Datum</th><th>Soort</th><th>Omschrijving</th><th>Leverancier</th><th>Totaal</th></tr></thead><tbody>{selected.costs.map((x:any)=><tr key={x.id} className="border-t"><td className="py-2">{date(x.cost_date)}</td><td>{x.cost_type}</td><td>{x.description||'-'}</td><td>{x.supplier||'-'}</td><td>{money(Number(x.amount_ex_vat)+Number(x.vat_amount))}</td></tr>)}</tbody></table></section>
 <section className="rounded-2xl border bg-white p-4"><h3 className="font-bold mb-3">Onderhoud</h3>{selected.maintenance.length?selected.maintenance.map((x:any)=><div key={x.id} className="border-t py-2 text-sm"><b>{x.maintenance_type}</b> · {x.status} · gepland {date(x.planned_date)} · {x.supplier||'geen leverancier'}</div>):<p className="text-sm text-slate-500">Nog geen onderhoud geregistreerd.</p>}</section>
 </div>}
