'use client';
import {useEffect,useMemo,useState} from 'react';

type Tab='voorraad'|'leveranciers'|'inkoop'|'mutaties';
const euro=(n:any)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(n||0));
const emptySupplier={name:'',contact_person:'',email:'',phone:'',street:'',house_number:'',postal_code:'',city:'',kvk:'',vat_number:'',iban:'',payment_term:14,active:1,notes:''};
const emptyOrder=()=>({supplier_id:'',order_date:new Date().toISOString().slice(0,10),expected_date:'',status:'concept',notes:''});
const emptyItem=()=>({inventory_id:'',description:'',quantity:1,unit:'stuk',unit_price:0,vat_rate:21});

export default function Magazijn(){
 const [tab,setTab]=useState<Tab>('voorraad'),[data,setData]=useState<any>({suppliers:[],orders:[],items:[],inventory:[],movements:[]}),[query,setQuery]=useState(''),[supplier,setSupplier]=useState<any>(null),[order,setOrder]=useState<any>(null),[items,setItems]=useState<any[]>([emptyItem()]),[movement,setMovement]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const r=await fetch('/api/magazijn',{cache:'no-store'});const j=await r.json();setLoading(false);if(!r.ok)setError(j.error||'Laden mislukt');else{setData(j);setError('')}}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{const q=query.toLowerCase();const src=tab==='voorraad'?data.inventory:tab==='leveranciers'?data.suppliers:tab==='inkoop'?data.orders:data.movements;return (src||[]).filter((x:any)=>JSON.stringify(x).toLowerCase().includes(q))},[data,tab,query]);
 const low=(data.inventory||[]).filter((x:any)=>Number(x.stock)<=Number(x.min_stock));
 const value=(data.inventory||[]).reduce((a:number,x:any)=>a+Number(x.stock||0)*Number(x.purchase_price||0),0);
 async function saveSupplier(){const method=supplier.id?'PUT':'POST';const r=await fetch('/api/magazijn',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'supplier',data:supplier})});const j=await r.json();if(!r.ok)return setError(j.error||'Opslaan mislukt');setSupplier(null);await load()}
 async function saveOrder(){const r=await fetch('/api/magazijn',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'order',data:order,items})});const j=await r.json();if(!r.ok)return setError(j.error||'Opslaan mislukt');setOrder(null);setItems([emptyItem()]);await load()}
 async function receive(id:number){if(!confirm('Deze inkooporder volledig ontvangen en voorraad bijwerken?'))return;const r=await fetch('/api/magazijn',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'receive',id})});const j=await r.json();if(!r.ok)return setError(j.error||'Ontvangst mislukt');await load()}
 async function saveMovement(){const r=await fetch('/api/magazijn',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'movement',...movement})});const j=await r.json();if(!r.ok)return setError(j.error||'Mutatie mislukt');setMovement(null);await load()}
 const orderTotal=items.reduce((a,x)=>a+Number(x.quantity||0)*Number(x.unit_price||0)*(1+Number(x.vat_rate||0)/100),0);
 return <main className="wrap"><header><div><h1>Magazijnbeheer Pro</h1><p>Voorraad, leveranciers en inkooporders</p></div><div className="actions"><button onClick={()=>setMovement({inventory_id:'',movement_type:'in',quantity:1,notes:''})}>Voorraadmutatie</button><button onClick={()=>setSupplier({...emptySupplier})}>Leverancier</button><button className="primary" onClick={()=>setOrder(emptyOrder())}>Inkooporder</button></div></header>
 <section className="stats"><article><b>{data.inventory.length}</b><span>Artikelen</span></article><article><b>{low.length}</b><span>Lage voorraad</span></article><article><b>{euro(value)}</b><span>Voorraadwaarde</span></article><article><b>{data.orders.filter((x:any)=>!['ontvangen','geannuleerd'].includes(x.status)).length}</b><span>Open inkooporders</span></article></section>
 <nav>{(['voorraad','leveranciers','inkoop','mutaties'] as Tab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>
 <div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Zoeken..."/><button onClick={load}>Vernieuwen</button></div>{error&&<p className="error">{error}</p>}{loading?<p>Laden...</p>:<section className="panel">
 {tab==='voorraad'&&<table><thead><tr><th>SKU</th><th>Artikel</th><th>Locatie</th><th>Voorraad</th><th>Minimum</th><th>Inkoop</th><th>Waarde</th></tr></thead><tbody>{filtered.map((x:any)=><tr key={x.id} className={Number(x.stock)<=Number(x.min_stock)?'low':''}><td>{x.sku||'-'}</td><td><b>{x.name}</b><small>{x.category||''}</small></td><td>{x.location||'-'}</td><td>{x.stock} {x.unit}</td><td>{x.min_stock}</td><td>{euro(x.purchase_price)}</td><td>{euro(Number(x.stock)*Number(x.purchase_price))}</td></tr>)}</tbody></table>}
 {tab==='leveranciers'&&<div className="cards">{filtered.map((x:any)=><article className="card" key={x.id}><h3>{x.name}</h3><p>{x.contact_person||'Geen contactpersoon'}</p><p>{x.email||'-'}<br/>{x.phone||'-'}</p><p>{[x.street,x.house_number,x.postal_code,x.city].filter(Boolean).join(' ')||'Geen adres'}</p><button onClick={()=>setSupplier({...x})}>Wijzigen</button></article>)}</div>}
 {tab==='inkoop'&&<table><thead><tr><th>Nummer</th><th>Leverancier</th><th>Datum</th><th>Verwacht</th><th>Status</th><th>Totaal</th><th></th></tr></thead><tbody>{filtered.map((x:any)=><tr key={x.id}><td><b>{x.order_number}</b></td><td>{x.supplier_name||'-'}</td><td>{String(x.order_date).slice(0,10)}</td><td>{x.expected_date?String(x.expected_date).slice(0,10):'-'}</td><td><span className={'badge '+x.status}>{x.status}</span></td><td>{euro(x.total)}</td><td>{x.status!=='ontvangen'&&x.status!=='geannuleerd'&&<button onClick={()=>receive(x.id)}>Ontvangen</button>}</td></tr>)}</tbody></table>}
 {tab==='mutaties'&&<table><thead><tr><th>Datum</th><th>Artikel</th><th>Type</th><th>Aantal</th><th>Referentie</th><th>Notitie</th></tr></thead><tbody>{filtered.map((x:any)=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString('nl-NL')}</td><td>{x.sku?`${x.sku} - `:''}{x.inventory_name}</td><td>{x.movement_type}</td><td>{x.quantity}</td><td>{x.reference_type?`${x.reference_type} #${x.reference_id}`:'-'}</td><td>{x.notes||'-'}</td></tr>)}</tbody></table>}
 </section>}
 {supplier&&<Modal title={supplier.id?'Leverancier wijzigen':'Nieuwe leverancier'} close={()=>setSupplier(null)}><div className="grid">{[['name','Naam'],['contact_person','Contactpersoon'],['email','E-mail'],['phone','Telefoon'],['street','Straat'],['house_number','Huisnummer'],['postal_code','Postcode'],['city','Plaats'],['kvk','KvK'],['vat_number','BTW-nummer'],['iban','IBAN']].map(([k,l])=><label key={k}>{l}<input value={supplier[k]||''} onChange={e=>setSupplier({...supplier,[k]:e.target.value})}/></label>)}<label>Betaaltermijn<input type="number" value={supplier.payment_term||14} onChange={e=>setSupplier({...supplier,payment_term:Number(e.target.value)})}/></label><label className="wide">Notities<textarea value={supplier.notes||''} onChange={e=>setSupplier({...supplier,notes:e.target.value})}/></label></div><button className="primary" onClick={saveSupplier}>Opslaan</button></Modal>}
 {order&&<Modal title="Nieuwe inkooporder" close={()=>setOrder(null)}><div className="grid"><label>Leverancier<select value={order.supplier_id} onChange={e=>setOrder({...order,supplier_id:e.target.value})}><option value="">Selecteer...</option>{data.suppliers.filter((x:any)=>Number(x.active)!==0).map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Orderdatum<input type="date" value={order.order_date} onChange={e=>setOrder({...order,order_date:e.target.value})}/></label><label>Verwachte datum<input type="date" value={order.expected_date} onChange={e=>setOrder({...order,expected_date:e.target.value})}/></label><label>Status<select value={order.status} onChange={e=>setOrder({...order,status:e.target.value})}><option>concept</option><option>besteld</option></select></label></div><h3>Regels</h3>{items.map((x,i)=><div className="line" key={i}><select value={x.inventory_id} onChange={e=>{const inv=data.inventory.find((a:any)=>String(a.id)===e.target.value);const copy=[...items];copy[i]={...x,inventory_id:e.target.value,description:inv?.name||x.description,unit:inv?.unit||x.unit,unit_price:inv?.purchase_price||x.unit_price};setItems(copy)}}><option value="">Vrije regel</option>{data.inventory.map((a:any)=><option value={a.id} key={a.id}>{a.sku||''} {a.name}</option>)}</select><input placeholder="Omschrijving" value={x.description} onChange={e=>{const c=[...items];c[i]={...x,description:e.target.value};setItems(c)}}/><input type="number" min="0" step="0.01" value={x.quantity} onChange={e=>{const c=[...items];c[i]={...x,quantity:Number(e.target.value)};setItems(c)}}/><input type="number" min="0" step="0.01" value={x.unit_price} onChange={e=>{const c=[...items];c[i]={...x,unit_price:Number(e.target.value)};setItems(c)}}/><button onClick={()=>setItems(items.filter((_,n)=>n!==i))}>×</button></div>)}<button onClick={()=>setItems([...items,emptyItem()])}>+ Regel</button><h3>Totaal: {euro(orderTotal)}</h3><label>Notities<textarea value={order.notes} onChange={e=>setOrder({...order,notes:e.target.value})}/></label><button className="primary" onClick={saveOrder}>Inkooporder opslaan</button></Modal>}
 {movement&&<Modal title="Voorraadmutatie" close={()=>setMovement(null)}><div className="grid"><label>Artikel<select value={movement.inventory_id} onChange={e=>setMovement({...movement,inventory_id:e.target.value})}><option value="">Selecteer...</option>{data.inventory.map((x:any)=><option value={x.id} key={x.id}>{x.sku||''} {x.name}</option>)}</select></label><label>Type<select value={movement.movement_type} onChange={e=>setMovement({...movement,movement_type:e.target.value})}><option value="in">Inboeken</option><option value="uit">Uitboeken</option><option value="correctie">Correctie omhoog</option></select></label><label>Aantal<input type="number" min="0.001" step="0.001" value={movement.quantity} onChange={e=>setMovement({...movement,quantity:Number(e.target.value)})}/></label><label className="wide">Notitie<textarea value={movement.notes} onChange={e=>setMovement({...movement,notes:e.target.value})}/></label></div><button className="primary" onClick={saveMovement}>Mutatie verwerken</button></Modal>}
 <style jsx>{`*{box-sizing:border-box}.wrap{padding:28px;max-width:1500px;margin:auto;font-family:Arial,sans-serif;color:#172033}header{display:flex;justify-content:space-between;gap:20px;align-items:center}h1{margin:0}header p{color:#667085}.actions{display:flex;gap:10px;flex-wrap:wrap}button{border:1px solid #d0d5dd;background:white;border-radius:9px;padding:10px 14px;cursor:pointer}.primary,nav .active{background:#172033;color:white}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:24px 0}.stats article,.panel,.card{background:white;border:1px solid #eaecf0;border-radius:14px;padding:18px;box-shadow:0 3px 14px #1018280c}.stats b{display:block;font-size:25px}.stats span,small{display:block;color:#667085;margin-top:5px}nav{display:flex;gap:8px;margin-bottom:14px;text-transform:capitalize}.toolbar{display:flex;gap:10px;margin-bottom:14px}.toolbar input{flex:1}.panel{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:13px;border-bottom:1px solid #eaecf0;white-space:nowrap}.low{background:#fff3f0}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card h3{margin-top:0}.badge{padding:5px 9px;border-radius:20px;background:#eef2f6}.badge.ontvangen{background:#dcfae6;color:#067647}.error{background:#fee4e2;color:#b42318;padding:12px;border-radius:9px}input,select,textarea{width:100%;border:1px solid #d0d5dd;border-radius:8px;padding:10px;font:inherit}textarea{min-height:85px}.modal{position:fixed;inset:0;background:#10182888;display:grid;place-items:center;padding:20px;z-index:20}.modalbox{background:white;border-radius:16px;width:min(1050px,100%);max-height:92vh;overflow:auto;padding:22px}.modalhead{display:flex;justify-content:space-between;align-items:center}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin:15px 0}.grid label{display:grid;gap:6px}.wide{grid-column:1/-1}.line{display:grid;grid-template-columns:1.1fr 1.6fr .5fr .6fr auto;gap:8px;margin:8px 0}@media(max-width:900px){.stats{grid-template-columns:repeat(2,1fr)}.cards{grid-template-columns:1fr}.line{grid-template-columns:1fr}.grid{grid-template-columns:1fr}.wide{grid-column:auto}header{align-items:flex-start;flex-direction:column}}`}</style>
 </main>
}
function Modal({title,close,children}:any){return <div className="modal"><section className="modalbox"><div className="modalhead"><h2>{title}</h2><button onClick={close}>×</button></div>{children}</section></div>}
