'use client';
import {useEffect,useMemo,useState} from 'react';

type Item={id:number;sku:string;barcode?:string;name:string;category?:string;supplier?:string;unit:string;stock:number;reserved_stock:number;available_stock:number;min_stock:number;max_stock?:number;purchase_price:number;sales_price:number;vat_rate:number;location?:string;low_stock:number;stock_value:number};
type Movement={id:number;inventory_id:number;movement_type:string;quantity:number;notes?:string;created_at:string;inventory_name:string;sku:string};
const euro=(n:any)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(n||0));
const num=(n:any)=>new Intl.NumberFormat('nl-NL',{maximumFractionDigits:3}).format(Number(n||0));

export default function VoorraadPage(){
 const [data,setData]=useState<any>({items:[],movements:[],kpis:{}}),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[lowOnly,setLowOnly]=useState(false),[selected,setSelected]=useState<Item|null>(null),[notice,setNotice]=useState('');
 const [form,setForm]=useState<any>({sku:'',name:'',category:'',supplier:'',unit:'stuk',stock:0,min_stock:0,purchase_price:0,sales_price:0,vat_rate:21,location:''});
 const [movement,setMovement]=useState<any>({inventory_id:'',movement_type:'inkoop',quantity:1,notes:''});
 const [count,setCount]=useState<any>({inventory_id:'',counted_stock:0,notes:''});
 async function load(){setLoading(true);const r=await fetch('/api/voorraad');const j=await r.json();setData(j);setLoading(false)}
 useEffect(()=>{load()},[]);
 const items=useMemo(()=>data.items.filter((x:Item)=>{const s=q.toLowerCase();return(!s||[x.sku,x.name,x.category,x.location].some(v=>String(v||'').toLowerCase().includes(s)))&&(!lowOnly||x.low_stock)}),[data,q,lowOnly]);
 async function post(body:any){setNotice('');const r=await fetch('/api/voorraad',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setNotice(j.error||'Actie mislukt');return false}setNotice('Opgeslagen');await load();return true}
 async function create(e:any){e.preventDefault();if(await post({action:'create',data:form}))setForm({sku:'',name:'',category:'',supplier:'',unit:'stuk',stock:0,min_stock:0,purchase_price:0,sales_price:0,vat_rate:21,location:''})}
 async function mutate(e:any){e.preventDefault();if(await post({action:'movement',data:{...movement,quantity:Number(movement.quantity)}}))setMovement({...movement,quantity:1,notes:''})}
 async function inventoryCount(e:any){e.preventDefault();if(await post({action:'count',data:{...count,counted_stock:Number(count.counted_stock)}}))setCount({...count,counted_stock:0,notes:''})}
 const cls='rounded-xl border border-slate-200 bg-white p-4 shadow-sm';
 return <main className="min-h-screen bg-slate-50 p-4 md:p-8">
  <div className="mx-auto max-w-7xl space-y-6">
   <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h1 className="text-3xl font-bold text-slate-900">Voorraadbeheer Pro</h1><p className="text-slate-600">Artikelen, magazijnmutaties, tellingen en minimumvoorraad.</p></div><button onClick={load} className="rounded-lg bg-slate-900 px-4 py-2 text-white">Vernieuwen</button></div>
   {notice&&<div className="rounded-lg bg-amber-50 px-4 py-3 text-amber-900">{notice}</div>}
   <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
    {[['Artikelen',data.kpis.articles],['Lage voorraad',data.kpis.lowStock],['Uitverkocht',data.kpis.outOfStock],['Inkoopwaarde',euro(data.kpis.stockValue)],['Verkoopwaarde',euro(data.kpis.salesValue)]].map(([a,b])=><div className={cls} key={String(a)}><div className="text-sm text-slate-500">{a}</div><div className="mt-1 text-2xl font-bold">{b??0}</div></div>)}
   </section>
   <section className="grid gap-6 xl:grid-cols-3">
    <form onSubmit={create} className={cls+' space-y-3'}><h2 className="text-lg font-semibold">Nieuw artikel</h2><div className="grid grid-cols-2 gap-3"><input required placeholder="Artikelnummer" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})} className="rounded-lg border p-2"/><input required placeholder="Naam" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="rounded-lg border p-2"/></div><div className="grid grid-cols-2 gap-3"><input placeholder="Categorie" value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="rounded-lg border p-2"/><input placeholder="Leverancier" value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})} className="rounded-lg border p-2"/></div><div className="grid grid-cols-3 gap-3"><input type="number" step="0.001" placeholder="Beginvoorraad" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})} className="rounded-lg border p-2"/><input type="number" step="0.001" placeholder="Minimum" value={form.min_stock} onChange={e=>setForm({...form,min_stock:e.target.value})} className="rounded-lg border p-2"/><input placeholder="Eenheid" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} className="rounded-lg border p-2"/></div><div className="grid grid-cols-2 gap-3"><input type="number" step="0.01" placeholder="Inkoopprijs" value={form.purchase_price} onChange={e=>setForm({...form,purchase_price:e.target.value})} className="rounded-lg border p-2"/><input type="number" step="0.01" placeholder="Verkoopprijs" value={form.sales_price} onChange={e=>setForm({...form,sales_price:e.target.value})} className="rounded-lg border p-2"/></div><input placeholder="Magazijnlocatie" value={form.location} onChange={e=>setForm({...form,location:e.target.value})} className="w-full rounded-lg border p-2"/><button className="w-full rounded-lg bg-blue-600 px-4 py-2 font-medium text-white">Artikel toevoegen</button></form>
    <form onSubmit={mutate} className={cls+' space-y-3'}><h2 className="text-lg font-semibold">Voorraadmutatie</h2><select required value={movement.inventory_id} onChange={e=>setMovement({...movement,inventory_id:e.target.value})} className="w-full rounded-lg border p-2"><option value="">Kies artikel</option>{data.items.map((x:Item)=><option key={x.id} value={x.id}>{x.sku} · {x.name} ({num(x.stock)} {x.unit})</option>)}</select><select value={movement.movement_type} onChange={e=>setMovement({...movement,movement_type:e.target.value})} className="w-full rounded-lg border p-2"><option value="inkoop">Inkoop / ontvangst</option><option value="retour">Retour ontvangen</option><option value="correctie">Correctie</option><option value="verbruik">Verbruik / afboeking</option><option value="schade">Schade / verlies</option></select><input type="number" step="0.001" required value={movement.quantity} onChange={e=>setMovement({...movement,quantity:e.target.value})} className="w-full rounded-lg border p-2"/><p className="text-xs text-slate-500">Gebruik een negatief aantal voor afboeken.</p><textarea placeholder="Toelichting" value={movement.notes} onChange={e=>setMovement({...movement,notes:e.target.value})} className="w-full rounded-lg border p-2"/><button className="w-full rounded-lg bg-emerald-600 px-4 py-2 font-medium text-white">Mutatie verwerken</button></form>
    <form onSubmit={inventoryCount} className={cls+' space-y-3'}><h2 className="text-lg font-semibold">Voorraadtelling</h2><select required value={count.inventory_id} onChange={e=>{const item=data.items.find((x:Item)=>x.id===Number(e.target.value));setCount({...count,inventory_id:e.target.value,counted_stock:item?.stock||0})}} className="w-full rounded-lg border p-2"><option value="">Kies artikel</option>{data.items.map((x:Item)=><option key={x.id} value={x.id}>{x.sku} · {x.name}</option>)}</select><input type="number" min="0" step="0.001" required value={count.counted_stock} onChange={e=>setCount({...count,counted_stock:e.target.value})} className="w-full rounded-lg border p-2"/><textarea placeholder="Notitie bij telling" value={count.notes} onChange={e=>setCount({...count,notes:e.target.value})} className="w-full rounded-lg border p-2"/><button className="w-full rounded-lg bg-violet-600 px-4 py-2 font-medium text-white">Telling verwerken</button></form>
   </section>
   <section className={cls}><div className="mb-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><h2 className="text-xl font-semibold">Artikelen</h2><div className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Zoeken…" className="rounded-lg border p-2"/><button onClick={()=>setLowOnly(!lowOnly)} className={'rounded-lg px-3 py-2 '+(lowOnly?'bg-amber-500 text-white':'bg-slate-100')}>Lage voorraad</button></div></div>{loading?<p>Laden…</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-2">Artikel</th><th className="p-2">Categorie</th><th className="p-2">Locatie</th><th className="p-2 text-right">Voorraad</th><th className="p-2 text-right">Beschikbaar</th><th className="p-2 text-right">Inkoop</th><th className="p-2 text-right">Verkoop</th></tr></thead><tbody>{items.map((x:Item)=><tr key={x.id} onClick={()=>setSelected(x)} className={'cursor-pointer border-b hover:bg-slate-50 '+(x.low_stock?'bg-amber-50':'')}><td className="p-2"><div className="font-medium">{x.name}</div><div className="text-xs text-slate-500">{x.sku}</div></td><td className="p-2">{x.category||'—'}</td><td className="p-2">{x.location||'—'}</td><td className="p-2 text-right font-semibold">{num(x.stock)} {x.unit}</td><td className="p-2 text-right">{num(x.available_stock)}</td><td className="p-2 text-right">{euro(x.purchase_price)}</td><td className="p-2 text-right">{euro(x.sales_price)}</td></tr>)}</tbody></table></div>}</section>
   <section className={cls}><h2 className="mb-4 text-xl font-semibold">Laatste magazijnmutaties</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-2">Datum</th><th className="p-2">Artikel</th><th className="p-2">Type</th><th className="p-2 text-right">Aantal</th><th className="p-2">Notitie</th></tr></thead><tbody>{data.movements.slice(0,30).map((m:Movement)=><tr key={m.id} className="border-b"><td className="p-2">{new Date(m.created_at).toLocaleString('nl-NL')}</td><td className="p-2">{m.sku} · {m.inventory_name}</td><td className="p-2 capitalize">{m.movement_type}</td><td className={'p-2 text-right font-semibold '+(Number(m.quantity)<0?'text-red-600':'text-emerald-600')}>{Number(m.quantity)>0?'+':''}{num(m.quantity)}</td><td className="p-2">{m.notes||'—'}</td></tr>)}</tbody></table></div></section>
   {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={()=>setSelected(null)}><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><h3 className="text-xl font-bold">{selected.name}</h3><p className="text-slate-500">{selected.sku}</p></div><button onClick={()=>setSelected(null)}>✕</button></div><div className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><span className="text-slate-500">Voorraad</span><div className="text-lg font-semibold">{num(selected.stock)} {selected.unit}</div></div><div><span className="text-slate-500">Minimum</span><div className="text-lg font-semibold">{num(selected.min_stock)}</div></div><div><span className="text-slate-500">Inkoopwaarde</span><div className="text-lg font-semibold">{euro(selected.stock_value)}</div></div><div><span className="text-slate-500">Marge per stuk</span><div className="text-lg font-semibold">{euro(Number(selected.sales_price)-Number(selected.purchase_price))}</div></div></div></div></div>}
  </div>
 </main>
}
