'use client';
import {useEffect,useMemo,useState} from 'react';

type Mod='dashboard'|'customers'|'documents'|'inventory'|'vehicles'|'hours'|'expenses'|'planning'|'users'|'settings';
const labels:Record<Mod,string>={dashboard:'Dashboard',customers:'Klanten',documents:'Offertes & facturen',inventory:'Voorraad',vehicles:'Voertuigen',hours:'Urenregistratie',expenses:'Uitgaven',planning:'Planning',users:'Gebruikers',settings:'Instellingen'};
const customerEmpty={customer_number:'',type:'particulier',status:'actief',name:'',company_name:'',contact_person:'',street:'',house_number:'',postal_code:'',city:'',province:'Groningen',country:'Nederland',email:'',secondary_email:'',phone:'',mobile:'',website:'',kvk:'',vat_number:'',iban:'',payment_term:14,vat_rate:21,discount_percentage:0,direct_debit:0,recurring:0,payment_behavior:'normaal',tags:'',active:1,color:'#f5c400',logo_url:'',notes:''};
const empty:any={customers:customerEmpty,inventory:{sku:'',name:'',category:'',unit:'stuk',stock:0,min_stock:0,purchase_price:0,sale_price:0,supplier:'',location:''},vehicles:{name:'',type:'bedrijfsauto',license_plate:'',odometer:0,apk_date:'',insurance_date:'',notes:''},time_entries:{customer_id:null,work_date:'',start_time:'',end_time:'',break_minutes:0,hours:0,description:'',billable:1},expenses:{expense_date:'',category:'materiaal',supplier:'',description:'',amount_ex_vat:0,vat_amount:0,amount_inc_vat:0,payment_method:'bank',receipt_path:''},appointments:{customer_id:null,title:'',start_at:'',end_at:'',status:'gepland',location:'',notes:''},documents:{type:'offerte',number:'',customer_id:null,issue_date:new Date().toISOString().slice(0,10),due_date:'',status:'concept',subtotal:0,vat_total:0,total:0,notes:''},settings:{setting_key:'company_name',setting_value:'KlusHulp Noord'}};

export default function App(){
 const [mod,setMod]=useState<Mod>('dashboard'),[data,setData]=useState<any>({}),[session,setSession]=useState<any>(null),[editing,setEditing]=useState<any>(null),[search,setSearch]=useState(''),[customerStatus,setCustomerStatus]=useState('alle'),[selectedCustomer,setSelectedCustomer]=useState<any>(null);
 async function load(){const [d,s]=await Promise.all([fetch('/api/data').then(r=>r.json()),fetch('/api/auth/session').then(r=>r.json())]);setData(d);setSession(s);if(selectedCustomer){const fresh=d.customers?.find((x:any)=>x.id===selectedCustomer.id);if(fresh)setSelectedCustomer(fresh)}}
 useEffect(()=>{load()},[]);
 async function save(table:string,obj:any){const method=obj.id?'PUT':'POST';const body=obj.id?{table,id:obj.id,data:obj}:{table,data:obj};const r=await fetch('/api/data',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)alert((await r.json()).error||'Opslaan mislukt');else{setEditing(null);await load()}}
 async function del(table:string,id:number){if(confirm('Weet je zeker dat je dit wilt verwijderen?')){const r=await fetch('/api/data',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({table,id})});if(!r.ok)alert((await r.json()).error||'Verwijderen mislukt');else{setSelectedCustomer(null);load()}}}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.href='/login'}
 const rows=useMemo(()=>{const key:any=({customers:'customers',documents:'documents',inventory:'inventory',vehicles:'vehicles',hours:'time_entries',expenses:'expenses',planning:'appointments',settings:'settings'} as any)[mod];return (data[key]||[]).filter((x:any)=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase()))},[data,mod,search]);
 const customers=useMemo(()=>rows.filter((x:any)=>mod!=='customers'||customerStatus==='alle'||(customerStatus==='inactief'?Number(x.active)===0:x.status===customerStatus)),[rows,mod,customerStatus]);
 const low=(data.inventory||[]).filter((x:any)=>Number(x.stock)<=Number(x.min_stock));
 const open=(data.documents||[]).filter((x:any)=>x.type==='factuur'&&!['betaald','geannuleerd'].includes(x.status));
 const paid=(data.documents||[]).filter((x:any)=>x.type==='factuur'&&x.status==='betaald');
 const revenue=paid.reduce((a:number,x:any)=>a+Number(x.total||0),0),billableHours=(data.time_entries||[]).filter((x:any)=>Number(x.billable)===1).reduce((a:number,x:any)=>a+Number(x.hours||0),0);
 const upcoming=[...(data.appointments||[])].sort((a:any,b:any)=>String(a.start_at).localeCompare(String(b.start_at))).slice(0,6);
 const today=new Intl.DateTimeFormat('nl-NL',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
 function navigate(next:Mod,obj?:any){setMod(next);setEditing(obj||null);setSelectedCustomer(null)}
 return <div className="shell"><aside><div className="logo"><b>KHN</b><span>KlusHulp Noord</span><small>Administratie v6.2</small></div><nav>{(Object.keys(labels) as Mod[]).map(k=>(k!=='users'||session?.permissions?.includes('*')||session?.permissions?.includes('users.manage'))&&<button className={mod===k?'active':''} onClick={()=>navigate(k)} key={k}>{labels[k]}</button>)}</nav><div className="user"><b>{session?.name}</b><small>{session?.roles?.join(', ')}</small><button onClick={logout}>Uitloggen</button></div></aside><main><header><div><h1>{labels[mod]}</h1><p>Betaalbaar • Betrouwbaar • Voor Iedereen</p></div>{mod!=='dashboard'&&mod!=='users'&&<button onClick={()=>setEditing({...empty[(({hours:'time_entries',planning:'appointments'} as any)[mod]||mod)]})}>+ Nieuw</button>}</header>
 {mod==='dashboard'?<Dashboard {...{data,session,today,revenue,paid,open,billableHours,upcoming,low,navigate}}/>:mod==='customers'?<Customers customers={customers} all={data.customers||[]} documents={data.documents||[]} appointments={data.appointments||[]} search={search} setSearch={setSearch} status={customerStatus} setStatus={setCustomerStatus} openCustomer={setSelectedCustomer} edit={setEditing} remove={del}/>:mod==='users'?<Users/>:<GenericTable mod={mod} rows={rows} search={search} setSearch={setSearch} edit={setEditing} remove={del}/>} 
 {selectedCustomer&&<CustomerDetail customer={selectedCustomer} documents={data.documents||[]} appointments={data.appointments||[]} hours={data.time_entries||[]} close={()=>setSelectedCustomer(null)} edit={()=>setEditing(selectedCustomer)} createDocument={(type:string)=>navigate('documents',{...empty.documents,type,customer_id:selectedCustomer.id})} createAppointment={()=>navigate('planning',{...empty.appointments,customer_id:selectedCustomer.id,title:`Afspraak ${displayName(selectedCustomer)}`,location:address(selectedCustomer)})}/>} 
 {editing&&(mod==='customers'||editing.customer_number!==undefined)?<CustomerEditor value={editing} close={()=>setEditing(null)} save={(v:any)=>save('customers',v)}/>:editing&&<Editor title={labels[mod]} value={editing} table={({hours:'time_entries',planning:'appointments'} as any)[mod]||mod} onClose={()=>setEditing(null)} onSave={save} customers={data.customers||[]}/>} 
 </main></div>
}

function Dashboard({data,session,today,revenue,paid,open,billableHours,upcoming,low,navigate}:any){return <section><div className="dashboardWelcome"><div><h2>Goed bezig, <strong>{session?.name?.split(' ')[0]||'Jochem'}</strong> 👋</h2><p>Dit is het actuele overzicht van KlusHulp Noord.</p></div><div className="dashboardBadge"><b>{today}</b><span>Administratie v6.2</span></div></div><div className="stats"><Stat n={data.customers?.length||0} l="Klanten" s="Totaal geregistreerd"/><Stat n={'€ '+revenue.toFixed(2)} l="Betaalde omzet" s={`${paid.length} betaalde facturen`}/><Stat n={open.length} l="Openstaande facturen" s={open.length?'Actie aanbevolen':'Alles bijgewerkt'}/><Stat n={billableHours.toFixed(1)} l="Declarabele uren" s="Nog te verwerken"/></div><div className="grid2"><div className="panel"><div className="panelHead"><div><h2>Planning</h2><small>Vandaag en binnenkort</small></div><button className="small" onClick={()=>navigate('planning')}>Open planning</button></div>{upcoming.map((x:any)=>{const d=x.start_at?new Date(x.start_at):null;return <div className="appointment" key={x.id}><div className="dateBox"><b>{d&&!isNaN(d.getTime())?d.getDate():'–'}</b><span>{d&&!isNaN(d.getTime())?d.toLocaleDateString('nl-NL',{month:'short'}):'datum'}</span></div><div className="appointmentContent"><b>{x.title}</b><small>{x.start_at||'Geen datum'}{x.location?` • ${x.location}`:''}</small></div></div>})}{!upcoming.length&&<p className="empty">Nog geen afspraken gepland.</p>}<div className="quickActions"><button onClick={()=>navigate('customers',{...customerEmpty})}>+ Klant</button><button onClick={()=>navigate('documents',{...empty.documents})}>+ Offerte</button><button onClick={()=>navigate('planning',{...empty.appointments})}>+ Afspraak</button></div></div><div className="panel"><div className="panelHead"><div><h2>Aandacht nodig</h2><small>Controlepunten voor vandaag</small></div></div>{low.map((x:any)=><div className="attention" key={x.id}><div className="attentionIcon">⚠️</div><div><b>{x.name}</b><br/><small>Voorraad: {x.stock} {x.unit} • minimum {x.min_stock}</small></div></div>)}{open.slice(0,4).map((x:any)=><div className="attention" key={'invoice-'+x.id}><div className="attentionIcon">📄</div><div><b>Factuur {x.number||'#'+x.id}</b><br/><small>{x.status} • € {Number(x.total||0).toFixed(2)}</small></div></div>)}{!low.length&&!open.length&&<p>✅ Alles ziet er goed uit.</p>}</div></div></section>}

function Customers({customers,all,documents,appointments,search,setSearch,status,setStatus,openCustomer,edit,remove}:any){
 const active=all.filter((x:any)=>Number(x.active)!==0).length,business=all.filter((x:any)=>x.type==='zakelijk').length,prospects=all.filter((x:any)=>x.status==='prospect').length;
 return <section><div className="customerStats"><Stat n={all.length} l="Totaal"/><Stat n={active} l="Actief"/><Stat n={business} l="Zakelijk"/><Stat n={prospects} l="Prospects"/></div><div className="customerToolbar"><input placeholder="Zoek op naam, bedrijf, telefoon, e-mail, KvK, plaats of postcode..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="alle">Alle klanten</option><option value="actief">Actief</option><option value="prospect">Prospect</option><option value="oud-klant">Oud-klant</option><option value="inactief">Inactief</option></select></div><div className="customerGrid">{customers.map((c:any)=>{const docs=documents.filter((d:any)=>Number(d.customer_id)===Number(c.id)),open=docs.filter((d:any)=>d.type==='factuur'&&!['betaald','geannuleerd'].includes(d.status)).reduce((a:number,d:any)=>a+Number(d.total||0),0),next=appointments.filter((a:any)=>Number(a.customer_id)===Number(c.id)).sort((a:any,b:any)=>String(a.start_at).localeCompare(String(b.start_at)))[0];return <article className="customerCard" key={c.id} style={{borderTopColor:c.color||'#f5c400'}}><div className="customerCardHead"><div className="avatar">{c.logo_url?<img src={c.logo_url} alt=""/>:(displayName(c)[0]||'?').toUpperCase()}</div><div><h3>{displayName(c)}</h3><span className={`badge ${c.status||'actief'}`}>{c.status||'actief'}</span> <span className="typeBadge">{c.type}</span></div></div><div className="customerMeta"><span>📍 {c.city||'Geen plaats'}</span><span>✉️ {c.email||'Geen e-mail'}</span><span>📞 {c.mobile||c.phone||'Geen telefoon'}</span></div><div className="customerMiniStats"><div><b>€ {open.toFixed(2)}</b><small>Openstaand</small></div><div><b>{docs.length}</b><small>Documenten</small></div></div>{next&&<div className="nextAppointment">📅 {formatDate(next.start_at)} — {next.title}</div>}<div className="cardActions"><button onClick={()=>openCustomer(c)}>Open</button><button className="secondary" onClick={()=>edit(c)}>Wijzig</button><button className="danger ghostDanger" onClick={()=>remove('customers',c.id)}>×</button></div></article>})}{!customers.length&&<div className="panel empty">Geen klanten gevonden.</div>}</div></section>
}

function CustomerDetail({customer,documents,appointments,hours,close,edit,createDocument,createAppointment}:any){
 const docs=documents.filter((d:any)=>Number(d.customer_id)===Number(customer.id)),paid=docs.filter((d:any)=>d.type==='factuur'&&d.status==='betaald').reduce((a:number,d:any)=>a+Number(d.total||0),0),outstanding=docs.filter((d:any)=>d.type==='factuur'&&!['betaald','geannuleerd'].includes(d.status)).reduce((a:number,d:any)=>a+Number(d.total||0),0),customerHours=hours.filter((h:any)=>Number(h.customer_id)===Number(customer.id)).reduce((a:number,h:any)=>a+Number(h.hours||0),0),next=appointments.filter((a:any)=>Number(a.customer_id)===Number(customer.id)).sort((a:any,b:any)=>String(a.start_at).localeCompare(String(b.start_at))).slice(0,5);
 return <div className="modal"><div className="panel customerDetail"><div className="editorhead"><div><small>{customer.customer_number||'Klant'}</small><h2>{displayName(customer)}</h2></div><button onClick={close}>×</button></div><div className="detailHero"><div className="avatar large">{customer.logo_url?<img src={customer.logo_url} alt=""/>:(displayName(customer)[0]||'?').toUpperCase()}</div><div><span className={`badge ${customer.status||'actief'}`}>{customer.status||'actief'}</span> <span className="typeBadge">{customer.type}</span><p>{address(customer)||'Geen adres ingevuld'}</p></div><button onClick={edit}>Gegevens wijzigen</button></div><div className="detailStats"><Stat n={`€ ${outstanding.toFixed(2)}`} l="Openstaand"/><Stat n={`€ ${paid.toFixed(2)}`} l="Totale omzet"/><Stat n={docs.length} l="Documenten"/><Stat n={customerHours.toFixed(1)} l="Uren"/></div><div className="detailColumns"><div><h3>Contact</h3><Info l="E-mail" v={customer.email} href={customer.email?`mailto:${customer.email}`:''}/><Info l="Tweede e-mail" v={customer.secondary_email} href={customer.secondary_email?`mailto:${customer.secondary_email}`:''}/><Info l="Telefoon" v={customer.phone} href={customer.phone?`tel:${customer.phone}`:''}/><Info l="Mobiel" v={customer.mobile} href={customer.mobile?`tel:${customer.mobile}`:''}/><Info l="Website" v={customer.website} href={customer.website}/><Info l="Adres" v={address(customer)} href={address(customer)?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address(customer))}`:''}/></div><div><h3>Bedrijf & financieel</h3><Info l="Contactpersoon" v={customer.contact_person}/><Info l="KvK" v={customer.kvk}/><Info l="BTW-nummer" v={customer.vat_number}/><Info l="IBAN" v={customer.iban}/><Info l="Betaaltermijn" v={`${customer.payment_term||14} dagen`}/><Info l="BTW-tarief" v={`${customer.vat_rate??21}%`}/><Info l="Korting" v={`${customer.discount_percentage??0}%`}/></div></div>{customer.tags&&<div className="tags">{String(customer.tags).split(',').map((t:string)=><span key={t}>{t.trim()}</span>)}</div>}<div className="notesBox"><h3>Notities</h3><p>{customer.notes||'Geen notities.'}</p></div><div className="detailColumns"><div><h3>Recente documenten</h3>{docs.slice(0,5).map((d:any)=><div className="listRow" key={d.id}><span>{d.type} {d.number||'#'+d.id}</span><b>€ {Number(d.total||0).toFixed(2)}</b></div>)}{!docs.length&&<p className="muted">Nog geen documenten.</p>}</div><div><h3>Planning</h3>{next.map((a:any)=><div className="listRow" key={a.id}><span>{formatDate(a.start_at)}</span><b>{a.title}</b></div>)}{!next.length&&<p className="muted">Geen afspraken.</p>}</div></div><div className="detailActions"><button onClick={()=>createDocument('offerte')}>+ Offerte</button><button onClick={()=>createDocument('factuur')}>+ Factuur</button><button onClick={createAppointment}>+ Afspraak</button><button className="secondary" onClick={close}>Sluiten</button></div></div></div>
}

function CustomerEditor({value,close,save}:any){const [v,setV]=useState({...customerEmpty,...value});const set=(k:string,val:any)=>setV((x:any)=>({...x,[k]:val}));const fields:any[]=[
 ['Basis',[['type','Type','select',['particulier','zakelijk']],['status','Status','select',['actief','prospect','oud-klant']],['active','Actief','bool'],['customer_number','Klantnummer','text'],['name','Naam','text'],['company_name','Bedrijfsnaam','text'],['contact_person','Contactpersoon','text'],['logo_url','Logo/foto URL','url'],['color','Planningkleur','color'],['tags','Tags (komma gescheiden)','text']]],
 ['Contact',[['email','E-mail','email'],['secondary_email','Tweede e-mail','email'],['phone','Telefoon','tel'],['mobile','Mobiel','tel'],['website','Website','url']]],
 ['Adres',[['street','Straat','text'],['house_number','Huisnummer','text'],['postal_code','Postcode','text'],['city','Plaats','text'],['province','Provincie','text'],['country','Land','text']]],
 ['Financieel',[['kvk','KvK-nummer','text'],['vat_number','BTW-nummer','text'],['iban','IBAN','text'],['payment_term','Betaaltermijn (dagen)','number'],['vat_rate','BTW-tarief %','number'],['discount_percentage','Korting %','number'],['direct_debit','Automatische incasso','bool'],['recurring','Terugkerende klant','bool'],['payment_behavior','Betaalgedrag','select',['normaal','goed','aandacht','slecht']]]]
 ];return <div className="modal"><div className="panel editor customerEditor"><div className="editorhead"><div><small>{v.id?'Klant bewerken':'Nieuwe klant'}</small><h2>{displayName(v)||'Klantgegevens'}</h2></div><button onClick={close}>×</button></div>{fields.map(([title,items])=><section className="formSection" key={title}><h3>{title}</h3><div className="formgrid">{items.map(([k,l,t,opts]:any)=><label key={k}>{l}{t==='select'?<select value={v[k]??''} onChange={e=>set(k,e.target.value)}>{opts.map((o:string)=><option key={o} value={o}>{o}</option>)}</select>:t==='bool'?<select value={Number(v[k]||0)} onChange={e=>set(k,Number(e.target.value))}><option value={1}>Ja</option><option value={0}>Nee</option></select>:<input type={t} value={v[k]??''} onChange={e=>set(k,t==='number'?Number(e.target.value):e.target.value)}/>}</label>)}</div></section>)}<section className="formSection"><h3>Notities</h3><textarea value={v.notes||''} onChange={e=>set('notes',e.target.value)} placeholder="Afspraken, voorkeuren, bijzonderheden..."/></section><div className="actions stickyActions"><button className="secondary" onClick={close}>Annuleren</button><button onClick={()=>save(v)}>Klant opslaan</button></div></div></div>}

function GenericTable({mod,rows,search,setSearch,edit,remove}:any){return <section><div className="toolbar"><input placeholder="Zoeken..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="panel tablewrap"><table><thead><tr>{columns(mod).map((c:any)=><th key={c.k}>{c.l}</th>)}<th>Acties</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}>{columns(mod).map((c:any)=><td key={c.k}>{fmt(x[c.k],c.k)}</td>)}<td><button className="small" onClick={()=>edit(x)}>Wijzig</button> <button className="small danger" onClick={()=>remove(({hours:'time_entries',planning:'appointments'} as any)[mod]||mod,x.id)}>Verwijder</button></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">Nog geen gegevens.</p>}</div></section>}
function Stat({n,l,s}:{n:any,l:string,s?:string}){return <div className="stat"><b>{n}</b><span>{l}</span>{s&&<small>{s}</small>}</div>}
function Info({l,v,href}:{l:string,v:any,href?:string}){return <div className="infoRow"><small>{l}</small>{v?(href?<a href={href} target={href.startsWith('http')?'_blank':undefined}>{v}</a>:<b>{v}</b>):<span>Niet ingevuld</span>}</div>}
function displayName(c:any){return c?.company_name||c?.name||c?.contact_person||''}
function address(c:any){return [c?.street,c?.house_number,c?.postal_code,c?.city,c?.country].filter(Boolean).join(' ')}
function formatDate(v:any){if(!v)return 'Geen datum';const d=new Date(v);return isNaN(d.getTime())?String(v):d.toLocaleString('nl-NL',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function columns(m:Mod){const c:any={documents:[['number','Nummer'],['type','Type'],['issue_date','Datum'],['status','Status'],['total','Totaal']],inventory:[['sku','Artikel'],['name','Omschrijving'],['stock','Voorraad'],['min_stock','Minimum'],['sale_price','Verkoopprijs'],['supplier','Leverancier']],vehicles:[['name','Voertuig'],['type','Type'],['license_plate','Kenteken'],['odometer','Kilometerstand'],['apk_date','APK']],hours:[['work_date','Datum'],['description','Omschrijving'],['start_time','Start'],['end_time','Einde'],['hours','Uren']],expenses:[['expense_date','Datum'],['category','Categorie'],['supplier','Leverancier'],['description','Omschrijving'],['amount_inc_vat','Bedrag']],planning:[['start_at','Start'],['title','Afspraak'],['location','Locatie'],['status','Status']],settings:[['setting_key','Instelling'],['setting_value','Waarde']]};return (c[m]||[]).map((x:any)=>({k:x[0],l:x[1]}))}
function fmt(v:any,k:string){if(k.includes('price')||k.includes('amount')||k==='total')return '€ '+Number(v||0).toFixed(2);if(v===1)return 'Ja';if(v===0)return 'Nee';return v??''}
function Editor({title,value,table,onClose,onSave,customers}:{title:string,value:any,table:string,onClose:()=>void,onSave:any,customers:any[]}){const [v,setV]=useState(value);return <div className="modal"><div className="panel editor"><div className="editorhead"><h2>{value.id?'Bewerken':'Nieuw'} — {title}</h2><button onClick={onClose}>×</button></div><div className="formgrid">{Object.keys(v).filter(k=>!['id','created_at','updated_at'].includes(k)).map(k=><label key={k}>{pretty(k)}{k==='customer_id'?<select value={v[k]||''} onChange={e=>setV({...v,[k]:e.target.value||null})}><option value="">Geen klant</option>{customers.map(c=><option key={c.id} value={c.id}>{displayName(c)}</option>)}</select>:k==='notes'||k==='description'?<textarea value={v[k]??''} onChange={e=>setV({...v,[k]:e.target.value})}/>:<input type={inputType(k,v[k])} value={v[k]??''} onChange={e=>setV({...v,[k]:['stock','min_stock','purchase_price','sale_price','odometer','break_minutes','hours','amount_ex_vat','vat_amount','amount_inc_vat','subtotal','vat_total','total','payment_term','recurring','billable'].includes(k)?Number(e.target.value):e.target.value})}/>}</label>)}</div><div className="actions"><button className="secondary" onClick={onClose}>Annuleren</button><button onClick={()=>onSave(table,v)}>Opslaan</button></div></div></div>}
function pretty(k:string){return k.replaceAll('_',' ').replace(/^./,x=>x.toUpperCase())}
function inputType(k:string,v:any){if(k.includes('date'))return 'date';if(k.includes('_at'))return 'datetime-local';if(k.includes('time'))return 'time';if(k==='email')return 'email';if(typeof v==='number')return 'number';return 'text'}
function Users(){const [d,setD]=useState<any>({users:[],roles:[]}),[f,setF]=useState<any>({name:'',email:'',password:'',roleIds:[]});async function load(){setD(await fetch('/api/users').then(r=>r.json()))}useEffect(()=>{load()},[]);async function add(){const r=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});if(!r.ok)alert((await r.json()).error);else{setF({name:'',email:'',password:'',roleIds:[]});load()}}return <div className="grid2"><div className="panel"><h2>Gebruikers</h2>{d.users?.map((u:any)=><p key={u.id}><b>{u.name}</b><br/><small>{u.email} • {u.active?'Actief':'Uitgeschakeld'}</small></p>)}</div><div className="panel"><h2>Nieuwe gebruiker</h2><label>Naam<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>E-mail<input value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Wachtwoord<input type="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></label>{d.roles?.map((r:any)=><label className="check" key={r.id}><input type="checkbox" checked={f.roleIds.includes(r.id)} onChange={e=>setF({...f,roleIds:e.target.checked?[...f.roleIds,r.id]:f.roleIds.filter((x:number)=>x!==r.id)})}/>{r.label}</label>)}<button onClick={add}>Gebruiker aanmaken</button></div></div>}
