'use client';
import {useEffect,useState} from 'react';

const money=(v:any)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(v||0));
const date=(v:any)=>v?new Date(v).toLocaleDateString('nl-NL'):'–';

export default function KlantportaalPage({params}:{params:{token:string}}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[form,setForm]=useState({name:'',email:'',note:''});
 async function load(){setLoading(true);const r=await fetch(`/api/klantportaal/${params.token}`,{cache:'no-store'}),j=await r.json();setLoading(false);if(!r.ok)setError(j.error||'Document laden mislukt');else{setData(j);setError('')}}
 useEffect(()=>{load()},[]);
 async function respond(action:'accept'|'reject'){if(!form.name.trim()){setError('Vul je naam in.');return}if(action==='reject'&&!confirm('Weet je zeker dat je deze offerte wilt afwijzen?'))return;setBusy(true);const r=await fetch(`/api/klantportaal/${params.token}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...form})}),j=await r.json();setBusy(false);if(!r.ok){setError(j.error||'Reactie opslaan mislukt');return}await load()}
 if(loading)return <main className="shell"><section className="card"><p>Document laden…</p></section></main>;
 if(error&&!data)return <main className="shell"><section className="card error"><h1>Deze link werkt niet</h1><p>{error}</p></section></main>;
 const d=data.document,response=data.response,answered=response.accepted_at||response.rejected_at;
 return <main className="shell"><section className="card">
  <header><div><small>KlusHulp Noord</small><h1>{d.type==='offerte'?'Offerte':'Factuur'} {d.number}</h1><p>Voor {data.customer.name||'klant'}</p></div><span className={'status '+d.status}>{d.status}</span></header>
  {error&&<div className="alert">{error}</div>}
  <div className="meta"><div><small>Datum</small><b>{date(d.issue_date)}</b></div><div><small>{d.type==='factuur'?'Vervaldatum':'Geldig tot'}</small><b>{date(d.due_date)}</b></div><div><small>Totaal</small><b>{money(d.total)}</b></div></div>
  <div className="address"><div><small>Klant</small><strong>{data.customer.name}</strong>{data.customer.contact_person&&<span>{data.customer.contact_person}</span>}<span>{data.customer.address}</span><span>{data.customer.postal_code} {data.customer.city}</span></div><div><small>Van</small><strong>KlusHulp Noord</strong><span>Betaalbaar en betrouwbaar kluswerk</span></div></div>
  <div className="table"><div className="row head"><span>Omschrijving</span><span>Aantal</span><span>Prijs</span><span>BTW</span><span>Totaal</span></div>{data.items.map((x:any,i:number)=><div className="row" key={i}><span>{x.description}</span><span>{Number(x.quantity)} {x.unit||''}</span><span>{money(x.unit_price)}</span><span>{Number(x.vat_rate)}%</span><span>{money(x.line_total)}</span></div>)}</div>
  <div className="totals"><p><span>Subtotaal</span><b>{money(d.subtotal)}</b></p><p><span>BTW</span><b>{money(d.vat_total)}</b></p><p className="grand"><span>Totaal</span><b>{money(d.total)}</b></p></div>
  {d.notes&&<div className="notes"><small>Opmerking</small><p>{d.notes}</p></div>}
  {d.type==='factuur'&&d.external_payment_url&&d.payment_status!=='betaald'&&<a className="pay" href={d.external_payment_url}>Factuur veilig betalen via {d.external_payment_provider||'betaalprovider'}</a>}
  {d.type==='offerte'&&!answered&&<section className="response"><h2>Reageren op deze offerte</h2><div className="grid"><label>Naam<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>E-mailadres<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></div><label>Opmerking<textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Eventuele vraag of opmerking"/></label><div className="buttons"><button className="reject" disabled={busy} onClick={()=>respond('reject')}>Offerte afwijzen</button><button className="accept" disabled={busy} onClick={()=>respond('accept')}>Offerte accepteren</button></div><p className="legal">Door te accepteren bevestig je dat je akkoord gaat met de offerte en de vermelde werkzaamheden en bedragen.</p></section>}
  {answered&&<section className={'answered '+(response.accepted_at?'yes':'no')}><h2>{response.accepted_at?'Offerte geaccepteerd':'Offerte afgewezen'}</h2><p>Reactie van {response.signer_name} op {date(response.accepted_at||response.rejected_at)}.</p>{response.response_note&&<p>{response.response_note}</p>}</section>}
 </section><style jsx>{`*{box-sizing:border-box}.shell{min-height:100vh;background:#f2f4f7;padding:28px;color:#18212f}.card{max-width:980px;margin:auto;background:#fff;border-radius:20px;padding:32px;box-shadow:0 18px 60px #10182818}header{display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid #eaecf0;padding-bottom:22px}h1{margin:5px 0;font-size:34px}small,header p{color:#667085}.status{height:max-content;padding:8px 12px;border-radius:99px;background:#eef2f6;font-weight:800}.status.geaccepteerd,.status.betaald{background:#dcfce7;color:#166534}.status.afgewezen{background:#fee2e2;color:#991b1b}.alert,.error{background:#fee4e2;color:#912018;padding:14px;border-radius:12px;margin:18px 0}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:24px 0}.meta div,.notes{background:#f8fafc;border-radius:12px;padding:16px;display:grid;gap:4px}.address{display:grid;grid-template-columns:1fr 1fr;gap:30px;margin:25px 0}.address div{display:grid;gap:4px}.table{overflow:auto;border:1px solid #eaecf0;border-radius:12px}.row{display:grid;grid-template-columns:2.4fr .8fr 1fr .6fr 1fr;gap:12px;padding:13px;min-width:680px;border-bottom:1px solid #eaecf0}.row:last-child{border-bottom:0}.head{background:#f8fafc;font-size:12px;font-weight:800;color:#667085}.totals{margin:20px 0 20px auto;max-width:380px}.totals p{display:flex;justify-content:space-between;padding:7px 0;margin:0}.grand{border-top:2px solid #18212f;font-size:20px;margin-top:8px!important;padding-top:12px!important}.pay{display:block;text-align:center;background:#635bff;color:#fff;text-decoration:none;padding:15px;border-radius:12px;font-weight:800;margin:22px 0}.response{border-top:1px solid #eaecf0;margin-top:28px;padding-top:24px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}label{display:grid;gap:7px;margin:12px 0;font-weight:700}input,textarea{width:100%;border:1px solid #d0d5dd;border-radius:10px;padding:11px;font:inherit}textarea{min-height:100px}.buttons{display:flex;justify-content:flex-end;gap:10px;margin-top:14px}button{border:0;border-radius:10px;padding:12px 16px;font-weight:800;cursor:pointer}.accept{background:#067647;color:#fff}.reject{background:#fee2e2;color:#991b1b}.legal{color:#667085;font-size:12px}.answered{border-radius:14px;padding:20px;margin-top:25px}.answered.yes{background:#dcfce7;color:#166534}.answered.no{background:#fee2e2;color:#991b1b}@media(max-width:700px){.shell{padding:12px}.card{padding:20px}.meta,.address,.grid{grid-template-columns:1fr}h1{font-size:27px}.buttons{flex-direction:column-reverse}button{width:100%}}`}</style></main>
}
