'use client';
import {useEffect,useMemo,useState} from 'react';

const euro=(n:any)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(n||0));
const num=(n:any)=>new Intl.NumberFormat('nl-NL',{maximumFractionDigits:2}).format(Number(n||0));
const today=()=>new Date().toISOString().slice(0,10);
const yearStart=()=>`${new Date().getFullYear()}-01-01`;

export default function Rapportages(){
 const [from,setFrom]=useState(yearStart()),[to,setTo]=useState(today()),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);const r=await fetch(`/api/rapportages?from=${from}&to=${to}`,{cache:'no-store'}),j=await r.json();setLoading(false);if(!r.ok)setError(j.error||'Rapportage laden mislukt');else{setData(j);setError('')}}
 useEffect(()=>{load()},[]);
 const months=useMemo(()=>{const map:any={};for(const x of data?.monthlyRevenue||[])map[x.month]={month:x.month,revenue:Number(x.value)};for(const x of data?.monthlyCosts||[])map[x.month]={...(map[x.month]||{month:x.month,revenue:0}),costs:Number(x.value)};return Object.values(map).sort((a:any,b:any)=>a.month.localeCompare(b.month))},[data]);
 function csv(){if(!data)return;const rows=[['Rapportage','Waarde'],['Omzet',data.kpi.revenue],['Kosten',data.kpi.costs],['Brutowinst',data.kpi.gross_profit],['Klanten',data.kpi.customers],['Werkbonnen',data.kpi.work_orders],['Uren',data.kpi.hours],[],['Maand','Omzet','Kosten'],...months.map((x:any)=>[x.month,x.revenue||0,x.costs||0])];const text=rows.map((r:any[])=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv'}));a.download=`rapportage-${from}-${to}.csv`;a.click();URL.revokeObjectURL(a.href)}
 if(loading&&!data)return <main className="page"><h1>Rapportages Pro</h1><p>Laden...</p></main>;
 const k=data?.kpi||{};
 return <main className="page">
  <header><div><h1>Rapportages Pro</h1><p>Financiën, klanten, monteurs, magazijn en contracten.</p></div><div className="actions"><button onClick={()=>window.print()}>Afdrukken / PDF</button><button onClick={csv}>CSV exporteren</button></div></header>
  {error&&<div className="error">{error}</div>}
  <section className="filters"><label>Vanaf<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Tot<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={load}>Bijwerken</button></section>
  <section className="stats"><Card t="Omzet" v={euro(k.revenue)}/><Card t="Kosten" v={euro(k.costs)}/><Card t="Brutowinst" v={euro(k.gross_profit)}/><Card t="Open werkbonnen" v={num(k.open_work_orders)}/><Card t="Gewerkte uren" v={num(k.hours)}/><Card t="Klanten" v={num(k.customers)}/><Card t="Actieve contracten" v={num(k.active_contracts)}/><Card t="Voorraadwaarde" v={euro(k.inventory_purchase_value)}/></section>
  <section className="grid2"><Box title="Omzet en kosten per maand"><div className="bars">{months.map((x:any)=>{const max=Math.max(1,...months.flatMap((m:any)=>[m.revenue||0,m.costs||0]));return <div className="barrow" key={x.month}><span>{x.month}</span><div><i style={{width:`${(x.revenue||0)/max*100}%`}} title={euro(x.revenue)}/><em style={{width:`${(x.costs||0)/max*100}%`}} title={euro(x.costs)}/></div><b>{euro((x.revenue||0)-(x.costs||0))}</b></div>})}</div></Box><Box title="Operationeel"><Metric n="Totaal werkbonnen" v={data?.workOrders?.total}/><Metric n="Bezig" v={data?.workOrders?.bezig}/><Metric n="Gereed" v={data?.workOrders?.gereed}/><Metric n="Lage voorraad" v={k.low_stock}/><Metric n="Achterstallig onderhoud" v={k.overdue_visits}/><Metric n="Periodieke contractwaarde" v={euro(k.contract_value)}/></Box></section>
  <section className="grid3"><Table title="Topklanten" heads={['Klant','Facturen','Omzet']} rows={(data?.topCustomers||[]).map((x:any)=>[x.name,x.invoices,euro(x.revenue)])}/><Table title="Monteurs" heads={['Naam','Werkbonnen','Uren','Waarde']} rows={(data?.mechanics||[]).map((x:any)=>[x.name,x.work_orders,num(x.hours),euro(x.value)])}/><Table title="Meest gebruikte materialen" heads={['Materiaal','Aantal','Waarde']} rows={(data?.materials||[]).map((x:any)=>[x.description,num(x.quantity),euro(x.value)])}/></section>
  <style jsx>{`main{padding:28px;display:grid;gap:18px;background:#f8fafc;min-height:100vh}header,.actions,.filters{display:flex;justify-content:space-between;align-items:end;gap:12px}.actions,.filters{justify-content:flex-start}.filters{background:#fff;padding:14px;border:1px solid #e2e8f0;border-radius:14px}.filters label{display:grid;gap:5px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.grid2{display:grid;grid-template-columns:2fr 1fr;gap:14px}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card,.box{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:17px}.card{display:grid;gap:5px}.card b{font-size:24px}.card span,.metric span{color:#64748b}.metric{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #eee}.bars{display:grid;gap:10px}.barrow{display:grid;grid-template-columns:75px 1fr 105px;gap:10px;align-items:center}.barrow div{display:grid;gap:3px}.barrow i,.barrow em{height:9px;border-radius:6px;display:block;background:#2563eb;min-width:2px}.barrow em{background:#f59e0b}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid #eee;font-size:14px}input,button{font:inherit;padding:9px 12px;border:1px solid #cbd5e1;border-radius:9px}button{cursor:pointer;background:#fff}.error{background:#fee2e2;padding:12px;border-radius:10px}@media(max-width:1000px){.stats{grid-template-columns:repeat(2,1fr)}.grid2,.grid3{grid-template-columns:1fr}}@media print{.actions,.filters{display:none}main{padding:0;background:#fff}}`}</style>
 </main>
}
function Card({t,v}:{t:string,v:any}){return <article className="card"><span>{t}</span><b>{v}</b></article>}
function Box({title,children}:{title:string,children:any}){return <article className="box"><h2>{title}</h2>{children}</article>}
function Metric({n,v}:{n:string,v:any}){return <div className="metric"><span>{n}</span><b>{v??0}</b></div>}
function Table({title,heads,rows}:{title:string,heads:string[],rows:any[][]}){return <article className="box"><h2>{title}</h2><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>):<tr><td colSpan={heads.length}>Geen gegevens</td></tr>}</tbody></table></article>}
