'use client';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';

type Line={description:string;quantity:number;unit:string;unit_price:number;vat_rate:number;discount_percentage:number;line_type:string;inventory_id?:number|null};
const blankLine=():Line=>({description:'',quantity:1,unit:'stuk',unit_price:0,vat_rate:21,discount_percentage:0,line_type:'artikel',inventory_id:null});
const today=()=>new Date().toISOString().slice(0,10);
const plusDays=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const money=(v:number)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(v||0);

export default function DocumentEditor(){
 const params=useSearchParams(),id=Number(params.get('id')||0),preset=params.get('type')||'offerte',customerPreset=Number(params.get('customer')||0);
 const [meta,setMeta]=useState<any>({customers:[],inventory:[]}),[doc,setDoc]=useState<any>({id:0,type:preset,customer_id:customerPreset||'',issue_date:today(),due_date:plusDays(14),status:'concept',notes:''}),[lines,setLines]=useState<Line[]>([blankLine()]),[revisions,setRevisions]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/documents/manage').then(r=>r.json()).then(setMeta);if(id)fetch(`/api/documents/manage?id=${id}`).then(r=>r.json()).then(j=>{setDoc(j.document);setLines(j.items?.length?j.items:[blankLine()]);setRevisions(j.revisions||[])})},[id]);
 const totals=useMemo(()=>{let subtotal=0,vat=0;for(const l of lines){const net=Number(l.quantity||0)*Number(l.unit_price||0)*(1-Number(l.discount_percentage||0)/100);subtotal+=net;vat+=net*Number(l.vat_rate||0)/100}return{subtotal,vat,total:subtotal+vat}},[lines]);
 const customer=meta.customers.find((c:any)=>Number(c.id)===Number(doc.customer_id));
 function setLine(index:number,key:string,value:any){setLines(xs=>xs.map((x,i)=>i===index?{...x,[key]:value}:x))}
 function chooseInventory(index:number,value:string){const item=meta.inventory.find((x:any)=>Number(x.id)===Number(value));if(!item)return setLine(index,'inventory_id',null);setLines(xs=>xs.map((x,i)=>i===index?{...x,inventory_id:item.id,description:item.name,unit:item.unit||'stuk',unit_price:Number(item.sale_price||0)}:x))}
 async function save(){setBusy(true);setError('');const r=await fetch('/api/documents/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document:doc,items:lines})});const j=await r.json();setBusy(false);if(!r.ok)return setError(j.error||'Opslaan mislukt');location.href=`/documenten/${j.id}`}
 return <main className="builder"><div className="builderTop"><div><small>Administratie v6.3</small><h1>{id?'Document bewerken':'Nieuw document'}</h1></div><div className="topActions"><button className="light" onClick={()=>history.back()}>Annuleren</button><button disabled={busy} onClick={save}>{busy?'Opslaan…':'Opslaan en bekijken'}</button></div></div>{error&&<div className="errorBox">{error}</div>}
 <section className="builderGrid"><div className="workspace"><div className="card formCard"><h2>Documentgegevens</h2><div className="formgrid"><label>Type<select disabled={!!id} value={doc.type} onChange={e=>setDoc({...doc,type:e.target.value})}><option value="offerte">Offerte</option><option value="factuur">Factuur</option><option value="werkbon">Werkbon</option><option value="creditfactuur">Creditfactuur</option></select></label><label>Klant<select value={doc.customer_id||''} onChange={e=>{const c=meta.customers.find((x:any)=>Number(x.id)===Number(e.target.value));setDoc({...doc,customer_id:e.target.value,due_date:plusDays(Number(c?.payment_term||14))})}}><option value="">Selecteer klant</option>{meta.customers.map((c:any)=><option key={c.id} value={c.id}>{c.company_name||c.name||c.contact_person} · {c.customer_number}</option>)}</select></label><label>Documentdatum<input type="date" value={doc.issue_date||''} onChange={e=>setDoc({...doc,issue_date:e.target.value})}/></label><label>Geldig/vervaldatum<input type="date" value={doc.due_date||''} onChange={e=>setDoc({...doc,due_date:e.target.value})}/></label></div><label>Introductie en notities<textarea value={doc.notes||''} onChange={e=>setDoc({...doc,notes:e.target.value})} placeholder="Omschrijving, afspraken en voorwaarden…"/></label></div>
 <div className="card"><div className="sectionHead"><div><h2>Documentregels</h2><small>Materiaal, arbeid, kilometers en vrije tekst</small></div><button className="light" onClick={()=>setLines([...lines,blankLine()])}>+ Regel</button></div><div className="lineHeader"><span>Soort / omschrijving</span><span>Aantal</span><span>Eenheid</span><span>Prijs</span><span>Korting</span><span>BTW</span><span>Totaal</span><span></span></div>{lines.map((l,i)=>{const net=Number(l.quantity||0)*Number(l.unit_price||0)*(1-Number(l.discount_percentage||0)/100);return <div className="line" key={i}><div className="desc"><select value={l.line_type} onChange={e=>setLine(i,'line_type',e.target.value)}><option value="artikel">Artikel</option><option value="arbeid">Arbeid</option><option value="kilometers">Kilometers</option><option value="tekst">Vrije tekst</option></select><select value={l.inventory_id||''} onChange={e=>chooseInventory(i,e.target.value)}><option value="">Handmatige regel</option>{meta.inventory.map((x:any)=><option key={x.id} value={x.id}>{x.sku?`${x.sku} · `:''}{x.name}</option>)}</select><input placeholder="Omschrijving" value={l.description} onChange={e=>setLine(i,'description',e.target.value)}/></div><input type="number" step="0.01" value={l.quantity} onChange={e=>setLine(i,'quantity',Number(e.target.value))}/><input value={l.unit} onChange={e=>setLine(i,'unit',e.target.value)}/><input type="number" step="0.01" value={l.unit_price} onChange={e=>setLine(i,'unit_price',Number(e.target.value))}/><input type="number" step="0.01" value={l.discount_percentage} onChange={e=>setLine(i,'discount_percentage',Number(e.target.value))}/><select value={l.vat_rate} onChange={e=>setLine(i,'vat_rate',Number(e.target.value))}><option value={0}>0%</option><option value={9}>9%</option><option value={21}>21%</option></select><b>{money(net)}</b><button className="remove" onClick={()=>setLines(lines.length===1?[blankLine()]:lines.filter((_,n)=>n!==i))}>×</button></div>})}</div></div>
 <aside><div className="card preview"><div className="brand"><b>KHN</b><span>KLUSHULP <strong>NOORD</strong></span></div><div className="previewType"><span>{doc.type}</span><b>{doc.number||'Automatisch nummer'}</b></div><div className="previewCustomer"><small>Aan</small><b>{customer?.company_name||customer?.name||'Kies een klant'}</b><span>{customer?.customer_number||''}</span></div><div className="previewTotals"><div><span>Subtotaal</span><b>{money(totals.subtotal)}</b></div><div><span>BTW</span><b>{money(totals.vat)}</b></div><div className="grand"><span>Totaal</span><b>{money(totals.total)}</b></div></div><small>Het officiële opvolgende nummer wordt pas bij opslaan gereserveerd.</small></div>{revisions.length>0&&<div className="card"><h3>Revisiegeschiedenis</h3>{revisions.map(r=><div className="revision" key={r.id}><b>Revisie {r.revision_number}</b><span>{new Date(r.created_at).toLocaleString('nl-NL')}</span></div>)}</div>}</aside></section>
 <style jsx global>{`*{box-sizing:border-box}body{margin:0;background:#f2f3f5;color:#171717;font-family:Inter,Arial,sans-serif}.builder{max-width:1550px;margin:auto;padding:28px}.builderTop,.sectionHead{display:flex;justify-content:space-between;align-items:center;gap:16px}.builderTop{margin-bottom:22px}.builderTop h1{margin:4px 0}.builderTop small,.sectionHead small,.preview small{color:#6b7280}.topActions{display:flex;gap:10px}button{border:0;border-radius:10px;background:#171717;color:#fff;padding:11px 15px;font-weight:800;cursor:pointer}button.light{background:#fff;color:#171717;border:1px solid #ddd}.builderGrid{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:18px}.workspace{display:grid;gap:18px}.card{background:#fff;border:1px solid #e3e4e7;border-radius:16px;padding:20px;box-shadow:0 8px 25px #1018280a}.card h2,.card h3{margin-top:0}.formgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:0 14px}label{display:grid;gap:6px;margin-bottom:14px;font-size:13px;font-weight:800}input,select,textarea{width:100%;padding:10px;border:1px solid #d5d7db;border-radius:9px;background:#fff;font:inherit}textarea{min-height:110px}.lineHeader,.line{display:grid;grid-template-columns:minmax(280px,2fr) 80px 80px 100px 80px 80px 105px 35px;gap:8px;align-items:center}.lineHeader{padding:10px 0;color:#6b7280;font-size:12px;font-weight:800}.line{border-top:1px solid #eee;padding:12px 0}.desc{display:grid;grid-template-columns:110px 1fr;gap:6px}.desc input{grid-column:1/3}.line b{text-align:right}.remove{background:#fee4e2;color:#b42318;padding:8px}.brand{background:#111;color:#fff;padding:18px;border-bottom:5px solid #f5b400;text-align:center}.brand b{font-size:42px;color:#f5b400}.brand span{display:block;font-weight:900}.brand strong{color:#f5b400}.previewType,.previewCustomer{display:flex;flex-direction:column;padding:18px 0;border-bottom:1px solid #eee}.previewType span{text-transform:uppercase;font-size:20px;font-weight:900}.previewType b{color:#9a6b00}.previewTotals{padding:15px 0}.previewTotals div{display:flex;justify-content:space-between;padding:6px 0}.previewTotals .grand{border-top:2px solid #111;border-bottom:5px solid #f5b400;font-size:18px}.revision{display:flex;justify-content:space-between;border-top:1px solid #eee;padding:10px 0;font-size:12px}.errorBox{background:#fee4e2;color:#912018;padding:12px;border-radius:10px;margin-bottom:15px}@media(max-width:1100px){.builderGrid{grid-template-columns:1fr}.lineHeader{display:none}.line{grid-template-columns:repeat(4,1fr)}.desc{grid-column:1/-1}.line b{text-align:left}}@media(max-width:650px){.builder{padding:14px}.builderTop{align-items:flex-start;flex-direction:column}.formgrid{grid-template-columns:1fr}.line{grid-template-columns:1fr 1fr}.desc{grid-column:1/-1}.line b{grid-column:1/2}}`}</style></main>
}