'use client';
import {useEffect,useMemo,useState} from 'react';

const euro=(n:any)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(n||0));
const today=()=>new Date().toISOString().slice(0,10);
const blank=()=>({customer_id:'',name:'',description:'',status:'actief',start_date:today(),end_date:'',renewal_type:'geen',notice_days:30,interval_type:'maandelijks',interval_count:1,next_service_date:today(),assigned_to:'',location:'',amount:0,vat_rate:21,billing_interval:'maandelijks',next_invoice_date:today(),auto_create_work_order:1,auto_invoice:0,notes:''});

type Tab='contracten'|'onderhoud'|'facturatie';
export default function Contracten(){
 const [data,setData]=useState<any>({contracts:[],customers:[],visits:[],invoiceRuns:[]}),[tab,setTab]=useState<Tab>('contracten'),[form,setForm]=useState<any>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const r=await fetch('/api/contracten',{cache:'no-store'}),j=await r.json();setLoading(false);if(!r.ok)setError(j.error||'Laden mislukt');else{setData(j);setError('')}}
 useEffect(()=>{load()},[]);
 const post=async(body:any,method='POST')=>{const r=await fetch('/api/contracten',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok){setError(j.error||'Actie mislukt');return null}setError('');return j};
 async function save(){const j=await post({action:'contract',data:form});if(j){setForm(null);await load()}}
 async function generate(){const until=new Date(Date.now()+180*86400000).toISOString().slice(0,10);const j=await post({action:'generate',until});if(j)await load()}
 async function makeWorkOrder(id:number){const j=await post({action:'workorder',visit_id:id});if(j)await load()}
 async function complete(id:number){const j=await post({action:'complete',visit_id:id});if(j)await load()}
 const source=tab==='contracten'?data.contracts:tab==='onderhoud'?data.visits:data.invoiceRuns;
 const filtered=useMemo(()=>source.filter((x:any)=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[source,query]);
 const active=data.contracts.filter((x:any)=>x.status==='actief').length;
 const due=data.visits.filter((x:any)=>x.status!=='gereed'&&String(x.planned_date).slice(0,10)<=today()).length;
 const recurring=data.contracts.filter((x:any)=>Number(x.auto_invoice)===1).reduce((a:number,x:any)=>a+Number(x.amount||0),0);
 return <main className="page">
  <header><div><h1>Contractbeheer & Onderhoud</h1><p>Onderhoudscontracten, terugkerende bezoeken en facturatieplanning.</p></div><div className="actions"><button onClick={generate}>Planning genereren</button><button onClick={()=>setForm(blank())}>+ Nieuw contract</button></div></header>
  {error&&<div className="error">{error}</div>}
  <section className="stats"><article><b>{data.contracts.length}</b><span>Contracten</span></article><article><b>{active}</b><span>Actief</span></article><article><b>{due}</b><span>Achterstallig</span></article><article><b>{euro(recurring)}</b><span>Periodieke waarde</span></article></section>
  <nav className="tabs"><button className={tab==='contracten'?'active':''} onClick={()=>setTab('contracten')}>Contracten</button><button className={tab==='onderhoud'?'active':''} onClick={()=>setTab('onderhoud')}>Onderhoud</button><button className={tab==='facturatie'?'active':''} onClick={()=>setTab('facturatie')}>Facturatie</button></nav>
  <input className="search" placeholder="Zoeken..." value={query} onChange={e=>setQuery(e.target.value)}/>
  <section className="card">{loading?<p>Laden...</p>:tab==='contracten'?<div className="table"><div className="tr head"><span>Nummer</span><span>Klant</span><span>Contract</span><span>Volgende beurt</span><span>Bedrag</span><span>Status</span></div>{filtered.map((x:any)=><div className="tr" key={x.id}><span>{x.contract_number}</span><span>{x.customer_name}</span><span>{x.name}</span><span>{String(x.next_service_date||'').slice(0,10)||'-'}</span><span>{euro(x.amount)}</span><span className={'badge '+x.status}>{x.status}</span></div>)}</div>:tab==='onderhoud'?<div className="table"><div className="tr head"><span>Datum</span><span>Klant</span><span>Contract</span><span>Status</span><span>Werkbon</span><span>Actie</span></div>{filtered.map((x:any)=><div className="tr" key={x.id}><span>{String(x.planned_date).slice(0,10)}</span><span>{x.customer_name}</span><span>{x.contract_number} · {x.contract_name}</span><span>{x.status}</span><span>{x.work_order_id?'Aangemaakt':'-'}</span><span>{!x.work_order_id?<button onClick={()=>makeWorkOrder(x.id)}>Maak werkbon</button>:x.status!=='gereed'?<button onClick={()=>complete(x.id)}>Gereed</button>:'✓'}</span></div>)}</div>:<div className="table"><div className="tr head"><span>Factuurdatum</span><span>Klant</span><span>Contract</span><span>Bedrag</span><span>BTW</span><span>Status</span></div>{filtered.map((x:any)=><div className="tr" key={x.id}><span>{String(x.invoice_date).slice(0,10)}</span><span>{x.customer_name}</span><span>{x.contract_number}</span><span>{euro(x.amount)}</span><span>{x.vat_rate}%</span><span>{x.status}</span></div>)}</div>}</section>
  {form&&<div className="overlay"><div className="modal large"><h2>Nieuw onderhoudscontract</h2><div className="grid"><label>Klant<select value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">Selecteer klant</option>{data.customers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Contractnaam<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Startdatum<input type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value,next_service_date:e.target.value,next_invoice_date:e.target.value})}/></label><label>Einddatum<input type="date" value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></label><label>Onderhoudsinterval<select value={form.interval_type} onChange={e=>setForm({...form,interval_type:e.target.value})}><option value="wekelijks">Wekelijks</option><option value="maandelijks">Maandelijks</option><option value="kwartaal">Per kwartaal</option><option value="jaarlijks">Jaarlijks</option></select></label><label>Elke<input type="number" min="1" value={form.interval_count} onChange={e=>setForm({...form,interval_count:Number(e.target.value)})}/></label><label>Monteur<input value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})}/></label><label>Locatie<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Bedrag excl. BTW<input type="number" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></label><label>BTW<input type="number" value={form.vat_rate} onChange={e=>setForm({...form,vat_rate:Number(e.target.value)})}/></label><label>Factuurinterval<select value={form.billing_interval} onChange={e=>setForm({...form,billing_interval:e.target.value})}><option value="maandelijks">Maandelijks</option><option value="kwartaal">Per kwartaal</option><option value="jaarlijks">Jaarlijks</option></select></label><label className="check"><input type="checkbox" checked={!!form.auto_invoice} onChange={e=>setForm({...form,auto_invoice:e.target.checked?1:0})}/> Facturatie klaarzetten</label></div><label>Omschrijving<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Notities<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="actions"><button onClick={()=>setForm(null)}>Annuleren</button><button onClick={save}>Contract opslaan</button></div></div></div>}
  <style jsx>{`main{padding:28px;display:grid;gap:18px}header{display:flex;justify-content:space-between;gap:16px;align-items:center}.actions,.tabs{display:flex;gap:10px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stats article,.card{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:18px}.stats article{display:grid}.stats b{font-size:24px}.stats span{color:#64748b}.search,input,select,textarea,button{font:inherit}.search,input,select,textarea{border:1px solid #cbd5e1;border-radius:9px;padding:10px;width:100%}button{border:0;border-radius:9px;padding:10px 14px;cursor:pointer}.tabs .active{background:#111827;color:#fff}.table{display:grid}.tr{display:grid;grid-template-columns:1fr 1.2fr 1.5fr 1fr 1fr 1fr;gap:12px;padding:12px;border-bottom:1px solid #eee;align-items:center}.head{font-weight:700}.badge{padding:5px 9px;border-radius:20px;background:#e2e8f0}.badge.actief{background:#dcfce7}.error{background:#fee2e2;padding:12px;border-radius:10px}.overlay{position:fixed;inset:0;background:#0008;display:grid;place-items:center;z-index:50;padding:20px}.modal{background:#fff;border-radius:16px;padding:22px;max-width:900px;width:100%;max-height:90vh;overflow:auto}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.modal label{display:grid;gap:6px;margin:10px 0}.check{grid-template-columns:auto 1fr!important;align-items:center}.check input{width:auto}@media(max-width:800px){.stats,.grid{grid-template-columns:1fr 1fr}.tr{grid-template-columns:1fr 1fr}.head{display:none}header{align-items:flex-start;flex-direction:column}}`}</style>
 </main>
}
