'use client';
import {useEffect,useState} from 'react';

export default function AutomatiseringPage(){
 const [data,setData]=useState<any>({runs:[],due_recurring:0,overdue_invoices:0}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){setLoading(true);const r=await fetch('/api/facturatie/automation',{cache:'no-store'}),j=await r.json();setLoading(false);if(!r.ok)setError(j.error||'Laden mislukt');else{setData(j);setError('')}}
 useEffect(()=>{load()},[]);
 async function run(){if(!confirm('Automatisering nu uitvoeren?'))return;setBusy(true);setError('');setMessage('');const r=await fetch('/api/facturatie/automation',{method:'POST'}),j=await r.json();setBusy(false);if(!r.ok){setError(j.error||'Uitvoeren mislukt');return}setMessage(`${j.created_documents} facturen aangemaakt en ${j.created_reminders} herinneringen klaargezet.`);await load()}
 return <main className="wrap"><header><div><small>KlusHulp Noord ERP v8.4</small><h1>Facturatie-automatisering</h1><p>Periodieke facturen en betalingsherinneringen automatisch verwerken.</p></div><div className="actions"><a href="/facturatie">← Facturatie</a><button disabled={busy} onClick={run}>{busy?'Bezig…':'Nu uitvoeren'}</button></div></header>
 {error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}
 <section className="stats"><Stat label="Periodieke facturen klaar" value={data.due_recurring}/><Stat label="Openstaande te late facturen" value={data.overdue_invoices}/><Stat label="Laatste uitvoeringen" value={data.runs.length}/></section>
 <section className="card"><h2>Dagelijkse verwerking</h2><p>Iedere ochtend worden actieve periodieke facturen met een verstreken factuurdatum aangemaakt. Voor te late facturen wordt maximaal één nieuwe conceptherinnering per zeven dagen klaargezet.</p><div className="note"><b>Belangrijk:</b> herinneringen worden bewust als concept klaargezet. Zo kun je ze eerst controleren voordat ze vanuit het e-mailcentrum naar de klant gaan.</div></section>
 <section className="card"><h2>Uitvoeringsgeschiedenis</h2>{loading?<p>Laden…</p>:!data.runs.length?<p>Nog geen uitvoeringen geregistreerd.</p>:<div className="table"><div className="tr head"><span>Start</span><span>Status</span><span>Facturen</span><span>Herinneringen</span><span>Details</span></div>{data.runs.map((r:any)=><div className="tr" key={r.id}><span>{new Date(r.started_at).toLocaleString('nl-NL')}</span><span><i className={'badge '+r.status}>{r.status}</i></span><span>{r.created_documents}</span><span>{r.created_reminders}</span><span>{r.details||'–'}</span></div>)}</div>}</section>
 <section className="card"><h2>Vercel-instelling</h2><p>De route wordt dagelijks via Vercel Cron aangeroepen. Voeg in Vercel één geheime variabele toe:</p><code>CRON_SECRET=een-lange-willekeurige-geheime-waarde</code></section>
 <style jsx>{`*{box-sizing:border-box}.wrap{max-width:1250px;margin:auto;padding:28px;background:#f4f6f8;min-height:100vh;color:#18212f}header{display:flex;justify-content:space-between;gap:20px;align-items:center}h1{font-size:36px;margin:4px 0}h2{margin-top:0}header p,small,.card p{color:#667085}.actions{display:flex;gap:10px}.actions a,.actions button{border:0;border-radius:10px;padding:11px 15px;background:#172033;color:#fff;text-decoration:none;font-weight:700;cursor:pointer}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:20px 0}.stat,.card{background:#fff;border:1px solid #e4e7ec;border-radius:16px;padding:18px;box-shadow:0 8px 24px #1018280a}.stat{display:grid;gap:5px}.stat b{font-size:28px}.card{margin-bottom:14px}.note{background:#fffaeb;border:1px solid #fedf89;padding:13px;border-radius:10px}.table{overflow:auto}.tr{display:grid;grid-template-columns:1.2fr .7fr .5fr .7fr 2fr;gap:12px;padding:12px;border-bottom:1px solid #eee;align-items:center;min-width:800px}.head{font-weight:800;font-size:12px;color:#667085}.badge{display:inline-block;padding:5px 9px;border-radius:99px;background:#edf2f7;font-style:normal}.badge.success{background:#dcfce7}.badge.failed{background:#fee2e2}.badge.running{background:#fef3c7}.error,.success{padding:12px;border-radius:10px;margin:14px 0}.error{background:#fee4e2;color:#912018}.success{background:#dcfce7;color:#166534}code{display:block;background:#101828;color:#fff;padding:12px;border-radius:10px;overflow:auto}button:disabled{opacity:.6}@media(max-width:800px){header{flex-direction:column;align-items:flex-start}.stats{grid-template-columns:1fr}}`}</style>
 </main>
}
function Stat({label,value}:{label:string,value:any}){return <article className="stat"><small>{label}</small><b>{value}</b></article>}
