'use client';
import {useEffect,useMemo,useState} from 'react';

const money=(v:any)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(v||0));
const today=()=>new Date().toISOString().slice(0,10);
const customerName=(x:any)=>x.company_name||x.customer_name||x.name||'Onbekend';
type Tab='documenten'|'betalingen'|'herinneringen'|'periodiek';

export default function FacturatiePage(){
 const [data,setData]=useState<any>({documents:[],payments:[],reminders:[],recurring:[],customers:[],kpis:{}}),[tab,setTab]=useState<Tab>('documenten'),[query,setQuery]=useState(''),[form,setForm]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState<number|null>(null);
 async function load(){setLoading(true);const r=await fetch('/api/facturatie',{cache:'no-store'}),j=await r.json();setLoading(false);if(!r.ok)setError(j.error||'Laden mislukt');else{setData(j);setError('')}}
 useEffect(()=>{load()},[]);
 async function post(body:any){const r=await fetch('/api/facturatie',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok){setError(j.error||'Actie mislukt');return null}setError('');await load();return j}
 async function save(){if(!form)return;const ok=await post(form.kind==='recurring'?{action:'recurring',data:form.data}:{action:form.kind,...form.data});if(ok)setForm(null)}
 async function documentAction(action:string,d:any){const label=action==='convert_quote'?'deze offerte omzetten naar een factuur':'een creditfactuur maken voor deze factuur';if(!confirm(`Wil je ${label}?`))return;setBusy(d.id);const result=await post({action,document_id:d.id});setBusy(null);if(result?.id)location.href=`/facturatie/document/${result.id}`}
 const source=tab==='documenten'?data.documents:tab==='betalingen'?data.payments:tab==='herinneringen'?data.reminders:data.recurring;
 const rows=useMemo(()=>source.filter((x:any)=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[source,query]);
 const invoices=data.documents.filter((x:any)=>x.type==='factuur');
 function openPayment(doc?:any){setForm({kind:'payment',data:{document_id:doc?.id||'',amount:doc?.outstanding_amount||0,payment_date:today(),payment_method:'bank',reference:'',notes:''}})}
 function openReminder(doc?:any){setForm({kind:'reminder',data:{document_id:doc?.id||'',reminder_type:'herinnering',reminder_date:today(),due_date:'',status:'concept',subject:`Betalingsherinnering ${doc?.number||''}`,message:''}})}
 function openRecurring(){setForm({kind:'recurring',data:{customer_id:'',name:'',description:'',amount_ex_vat:0,vat_rate:21,interval_type:'maandelijks',next_invoice_date:today(),active:1}})}
 return <main className="wrap"><header><div><small>KlusHulp Noord ERP v8.2</small><h1>Facturatie Pro</h1><p>Offertes, facturen, betalingen, herinneringen en periodieke facturen.</p></div><div className="actions"><a href="/">Administratie</a><button onClick={()=>tab==='betalingen'?openPayment():tab==='herinneringen'?openReminder():tab==='periodiek'?openRecurring():location.href='/'}>+ Nieuw</button></div></header>
 {error&&<div className="error">{error}</div>}
 <section className="stats"><Stat label="Gefactureerd" value={money(data.kpis.invoiced)}/><Stat label="Betaald" value={money(data.kpis.paid)}/><Stat label="Openstaand" value={money(data.kpis.outstanding)}/><Stat label="Te laat" value={String(data.kpis.overdue||0)}/><Stat label="Open offertes" value={String(data.kpis.quotes||0)}/></section>
 <nav className="tabs"><button className={tab==='documenten'?'active':''} onClick={()=>setTab('documenten')}>Documenten</button><button className={tab==='betalingen'?'active':''} onClick={()=>setTab('betalingen')}>Betalingen</button><button className={tab==='herinneringen'?'active':''} onClick={()=>setTab('herinneringen')}>Herinneringen</button><button className={tab==='periodiek'?'active':''} onClick={()=>setTab('periodiek')}>Periodiek</button></nav>
 <section className="card"><div className="toolbar"><input placeholder="Zoeken..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{loading?<p>Laden…</p>:tab==='documenten'?<div className="table"><div className="tr head"><span>Nummer</span><span>Klant</span><span>Type</span><span>Datum</span><span>Totaal</span><span>Openstaand</span><span>Status</span><span>Acties</span></div>{rows.map((d:any)=><div className="tr" key={d.id}><span><b>{d.number||'#'+d.id}</b></span><span>{customerName(d)}</span><span>{d.type}</span><span>{String(d.issue_date||'').slice(0,10)}</span><span>{money(d.total)}</span><span>{d.type==='creditfactuur'?'–':money(d.outstanding_amount)}</span><span><i className={'badge '+(d.payment_status||d.status)}>{d.payment_status||d.status}</i></span><span className="mini"><a className="buttonLink" href={`/facturatie/document/${d.id}`}>PDF</a>{['factuur','creditfactuur'].includes(d.type)&&<a className="buttonLink ubl" href={`/api/facturatie/ubl/${d.id}`}>UBL</a>}{d.type==='offerte'&&<button disabled={busy===d.id} onClick={()=>documentAction('convert_quote',d)}>→ Factuur</button>}{d.type==='factuur'&&<><button onClick={()=>openPayment(d)}>Betaling</button><button onClick={()=>openReminder(d)}>Herinner</button><button disabled={busy===d.id} onClick={()=>documentAction('credit_invoice',d)}>Credit</button></>}</span></div>)}</div>:tab==='betalingen'?<div className="table"><div className="tr simple"><b>Datum</b><b>Factuur</b><b>Bedrag</b><b>Methode</b><b>Referentie</b></div>{rows.map((p:any)=><div className="tr simple" key={p.id}><span>{String(p.payment_date).slice(0,10)}</span><span>{p.document_number}</span><span>{money(p.amount)}</span><span>{p.payment_method}</span><span>{p.reference||'–'}</span></div>)}</div>:tab==='herinneringen'?<div className="table"><div className="tr simple"><b>Datum</b><b>Factuur</b><b>Klant</b><b>Type</b><b>Status</b></div>{rows.map((r:any)=><div className="tr simple" key={r.id}><span>{String(r.reminder_date).slice(0,10)}</span><span>{r.document_number}</span><span>{customerName(r)}</span><span>{r.reminder_type}</span><span>{r.status}</span></div>)}</div>:<div className="table"><div className="tr simple"><b>Klant</b><b>Naam</b><b>Bedrag excl.</b><b>Interval</b><b>Volgende datum</b></div>{rows.map((r:any)=><div className="tr simple" key={r.id}><span>{customerName(r)}</span><span>{r.name}</span><span>{money(r.amount_ex_vat)}</span><span>{r.interval_type}</span><span>{String(r.next_invoice_date).slice(0,10)}</span></div>)}</div>}</section>
 {form&&<div className="overlay"><div className="modal"><h2>{form.kind==='payment'?'Betaling registreren':form.kind==='reminder'?'Herinnering maken':'Periodieke factuur'}</h2>{form.kind!=='recurring'?<label>Factuur<select value={form.data.document_id} onChange={e=>setForm({...form,data:{...form.data,document_id:e.target.value}})}><option value="">Selecteer factuur</option>{invoices.map((x:any)=><option key={x.id} value={x.id}>{x.number} · {customerName(x)} · {money(x.outstanding_amount)}</option>)}</select></label>:<label>Klant<select value={form.data.customer_id} onChange={e=>setForm({...form,data:{...form.data,customer_id:e.target.value}})}><option value="">Selecteer klant</option>{data.customers.map((x:any)=><option key={x.id} value={x.id}>{customerName(x)}</option>)}</select></label>}
 {form.kind==='payment'&&<><label>Bedrag<input type="number" step="0.01" value={form.data.amount} onChange={e=>setForm({...form,data:{...form.data,amount:Number(e.target.value)}})}/></label><label>Datum<input type="date" value={form.data.payment_date} onChange={e=>setForm({...form,data:{...form.data,payment_date:e.target.value}})}/></label><label>Methode<select value={form.data.payment_method} onChange={e=>setForm({...form,data:{...form.data,payment_method:e.target.value}})}><option value="bank">Bank</option><option value="contant">Contant</option><option value="pin">Pin</option><option value="ideal">iDEAL</option></select></label><label>Referentie<input value={form.data.reference} onChange={e=>setForm({...form,data:{...form.data,reference:e.target.value}})}/></label></>}
 {form.kind==='reminder'&&<><label>Type<select value={form.data.reminder_type} onChange={e=>setForm({...form,data:{...form.data,reminder_type:e.target.value}})}><option value="herinnering">Herinnering</option><option value="aanmaning">Aanmaning</option><option value="laatste-aanmaning">Laatste aanmaning</option></select></label><label>Onderwerp<input value={form.data.subject} onChange={e=>setForm({...form,data:{...form.data,subject:e.target.value}})}/></label><label>Bericht<textarea value={form.data.message} onChange={e=>setForm({...form,data:{...form.data,message:e.target.value}})}/></label></>}
 {form.kind==='recurring'&&<><label>Naam<input value={form.data.name} onChange={e=>setForm({...form,data:{...form.data,name:e.target.value}})}/></label><label>Bedrag excl. BTW<input type="number" step="0.01" value={form.data.amount_ex_vat} onChange={e=>setForm({...form,data:{...form.data,amount_ex_vat:Number(e.target.value)}})}/></label><label>BTW %<input type="number" value={form.data.vat_rate} onChange={e=>setForm({...form,data:{...form.data,vat_rate:Number(e.target.value)}})}/></label><label>Interval<select value={form.data.interval_type} onChange={e=>setForm({...form,data:{...form.data,interval_type:e.target.value}})}><option value="maandelijks">Maandelijks</option><option value="kwartaal">Per kwartaal</option><option value="jaarlijks">Jaarlijks</option></select></label><label>Volgende factuur<input type="date" value={form.data.next_invoice_date} onChange={e=>setForm({...form,data:{...form.data,next_invoice_date:e.target.value}})}/></label></>}
 <div className="actions"><button className="secondary" onClick={()=>setForm(null)}>Annuleren</button><button onClick={save}>Opslaan</button></div></div></div>}
 <style jsx>{`*{box-sizing:border-box}.wrap{max-width:1550px;margin:auto;padding:28px;background:#f4f6f8;min-height:100vh;color:#18212f}header{display:flex;justify-content:space-between;gap:20px;align-items:center}h1{font-size:36px;margin:4px 0}header p,small{color:#667085}.actions,.tabs,.mini{display:flex;gap:9px;flex-wrap:wrap}.actions a,.actions button,button,.buttonLink{border:0;border-radius:10px;padding:10px 14px;background:#172033;color:#fff;text-decoration:none;font-weight:700;cursor:pointer}.ubl{background:#0f766e!important}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:20px 0}.stat,.card{background:#fff;border:1px solid #e4e7ec;border-radius:16px;padding:18px;box-shadow:0 8px 24px #1018280a}.stat{display:grid;gap:5px}.stat b{font-size:23px}.tabs{margin-bottom:12px}.tabs button{background:#e8ebf0;color:#344054}.tabs .active{background:#172033;color:#fff}.toolbar{display:flex;justify-content:flex-end;margin-bottom:12px}input,select,textarea{width:100%;border:1px solid #d0d5dd;border-radius:9px;padding:10px;font:inherit}.toolbar input{max-width:380px}.table{overflow:auto}.tr{display:grid;grid-template-columns:1fr 1.4fr .7fr .8fr .8fr .8fr .8fr 2.5fr;gap:10px;padding:12px;border-bottom:1px solid #eee;align-items:center;min-width:1300px}.tr.simple{grid-template-columns:repeat(5,1fr);min-width:750px}.head{font-weight:800;font-size:12px;color:#667085}.mini button,.buttonLink{padding:7px 9px;font-size:12px}.badge{display:inline-block;padding:5px 8px;border-radius:99px;background:#edf2f7;font-style:normal}.badge.betaald{background:#dcfce7}.badge.gedeeltelijk{background:#fef3c7}.error{background:#fee4e2;color:#912018;padding:12px;border-radius:10px;margin:14px 0}.overlay{position:fixed;inset:0;background:#0008;display:grid;place-items:center;z-index:50;padding:20px}.modal{background:#fff;border-radius:16px;padding:22px;width:min(620px,100%);max-height:90vh;overflow:auto}.modal label{display:grid;gap:6px;margin:12px 0}.secondary{background:#e5e7eb!important;color:#111827!important}button:disabled{opacity:.5;cursor:wait}@media(max-width:900px){.stats{grid-template-columns:1fr 1fr}header{align-items:flex-start;flex-direction:column}}`}</style>
 </main>
}
function Stat({label,value}:{label:string,value:string}){return <article className="stat"><small>{label}</small><b>{value}</b></article>}
