'use client';
import {useEffect,useMemo,useState} from 'react';

const euro=(v:any)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(v||0));
const today=()=>new Date().toISOString().slice(0,10);
type Tab='dashboard'|'grootboek'|'journaal'|'inkoop'|'btw';

export default function BoekhoudingPage(){
 const [data,setData]=useState<any>({accounts:[],entries:[],purchases:[],vat:[],kpis:{}}),[tab,setTab]=useState<Tab>('dashboard'),[year,setYear]=useState(new Date().getFullYear()),[loading,setLoading]=useState(true),[error,setError]=useState(''),[form,setForm]=useState<any>(null),[busy,setBusy]=useState<number|null>(null);
 async function load(){setLoading(true);const r=await fetch(`/api/boekhouding?year=${year}`,{cache:'no-store'}),j=await r.json();setLoading(false);if(!r.ok)setError(j.error||'Laden mislukt');else{setData(j);setError('')}}
 useEffect(()=>{load()},[year]);
 async function post(body:any){const r=await fetch('/api/boekhouding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok){setError(j.error||'Actie mislukt');return null}setError('');await load();return j}
 function openPurchase(){setForm({kind:'purchase',data:{supplier_name:'',invoice_number:'',invoice_date:today(),due_date:'',description:'',subtotal:0,vat_total:0,total:0,status:'open',ledger_account_id:''}})}
 function openAccount(){setForm({kind:'account',data:{code:'',name:'',type:'kosten',vat_code:'hoog',active:1}})}
 function openJournal(){setForm({kind:'journal',data:{entry_date:today(),description:'',reference:'',lines:[{ledger_account_id:'',description:'',debit:0,credit:0},{ledger_account_id:'',description:'',debit:0,credit:0}]}})}
 async function save(){if(!form)return;let body:any;if(form.kind==='purchase')body={action:'purchase',...form.data};else if(form.kind==='account')body={action:'account',...form.data};else body={action:'manual_journal',...form.data};const ok=await post(body);if(ok)setForm(null)}
 async function payPurchase(p:any){if(!confirm(`Inkoopfactuur ${p.invoice_number||p.supplier_name} als betaald boeken?`))return;setBusy(p.id);await post({action:'purchase_payment',id:p.id,payment_date:today(),reference:p.invoice_number});setBusy(null)}
 const years=useMemo(()=>Array.from({length:7},(_,i)=>new Date().getFullYear()-3+i),[]);
 return <main className="wrap"><header><div><small>KlusHulp Noord ERP v8.6</small><h1>Boekhouding Pro</h1><p>Grootboek, journaal, inkoop, BTW en resultaat in één overzicht.</p></div><div className="actions"><a href="/facturatie">Facturatie</a><a href="/">Administratie</a><select value={year} onChange={e=>setYear(Number(e.target.value))}>{years.map(y=><option key={y}>{y}</option>)}</select></div></header>
 {error&&<div className="error">{error}</div>}
 <section className="stats"><Stat label="Omzet" value={euro(data.kpis.revenue)}/><Stat label="Kosten" value={euro(data.kpis.costs)}/><Stat label="Resultaat" value={euro(data.kpis.profit)}/><Stat label="Inkoop" value={euro(data.kpis.purchases)}/><Stat label="Open crediteuren" value={euro(data.kpis.openPurchases)}/></section>
 <nav className="tabs"><button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}>Dashboard</button><button className={tab==='grootboek'?'active':''} onClick={()=>setTab('grootboek')}>Grootboek</button><button className={tab==='journaal'?'active':''} onClick={()=>setTab('journaal')}>Journaal</button><button className={tab==='inkoop'?'active':''} onClick={()=>setTab('inkoop')}>Inkoop</button><button className={tab==='btw'?'active':''} onClick={()=>setTab('btw')}>BTW</button></nav>
 {loading?<section className="card"><p>Laden…</p></section>:tab==='dashboard'?<section className="grid"><article className="card"><h2>Winst & verlies</h2><div className="metric"><span>Omzet</span><b>{euro(data.kpis.revenue)}</b></div><div className="metric"><span>Kosten</span><b>{euro(data.kpis.costs)}</b></div><div className="metric total"><span>Resultaat</span><b>{euro(data.kpis.profit)}</b></div></article><article className="card"><h2>Snel starten</h2><div className="quick"><button onClick={openPurchase}>+ Inkoopfactuur</button><button onClick={openJournal}>+ Journaalpost</button><button onClick={openAccount}>+ Grootboekrekening</button></div></article><article className="card wide"><h2>Recente journaalposten</h2><EntryTable entries={data.entries.slice(0,8)}/></article></section>:tab==='grootboek'?<section className="card"><div className="cardHead"><h2>Grootboekrekeningen</h2><button onClick={openAccount}>+ Rekening</button></div><div className="table"><div className="tr account head"><span>Code</span><span>Naam</span><span>Type</span><span>Debet</span><span>Credit</span><span>Saldo</span></div>{data.accounts.map((a:any)=><div className="tr account" key={a.id}><span><b>{a.code}</b></span><span>{a.name}</span><span>{a.type}</span><span>{euro(a.debit)}</span><span>{euro(a.credit)}</span><span><b>{euro(a.balance)}</b></span></div>)}</div></section>:tab==='journaal'?<section className="card"><div className="cardHead"><h2>Journaal</h2><button onClick={openJournal}>+ Journaalpost</button></div><EntryTable entries={data.entries}/></section>:tab==='inkoop'?<section className="card"><div className="cardHead"><h2>Inkoopfacturen</h2><button onClick={openPurchase}>+ Inkoopfactuur</button></div><div className="table"><div className="tr purchase head"><span>Datum</span><span>Leverancier</span><span>Factuurnummer</span><span>Boeking</span><span>Excl. BTW</span><span>BTW</span><span>Totaal</span><span>Status</span><span>Actie</span></div>{data.purchases.map((p:any)=><div className="tr purchase" key={p.id}><span>{String(p.invoice_date).slice(0,10)}</span><span><b>{p.supplier_name}</b></span><span>{p.invoice_number||'–'}</span><span>{p.ledger_code} {p.ledger_name}</span><span>{euro(p.subtotal)}</span><span>{euro(p.vat_total)}</span><span><b>{euro(p.total)}</b></span><span><i className={'badge '+p.status}>{p.status}</i></span><span>{p.status!=='betaald'&&<button disabled={busy===p.id} onClick={()=>payPurchase(p)}>Betaald</button>}</span></div>)}</div></section>:<section className="card"><h2>BTW-overzicht {year}</h2><div className="table"><div className="tr vat head"><span>Code</span><span>Rekening</span><span>Debet</span><span>Credit</span><span>BTW geregistreerd</span></div>{data.vat.map((v:any)=><div className="tr vat" key={v.code}><span><b>{v.code}</b></span><span>{v.name}</span><span>{euro(v.debit)}</span><span>{euro(v.credit)}</span><span><b>{euro(v.vat)}</b></span></div>)}</div></section>}
 {form&&<div className="overlay"><div className="modal"><h2>{form.kind==='purchase'?'Inkoopfactuur registreren':form.kind==='account'?'Grootboekrekening toevoegen':'Journaalpost maken'}</h2>{form.kind==='purchase'&&<><label>Leverancier<input value={form.data.supplier_name} onChange={e=>setForm({...form,data:{...form.data,supplier_name:e.target.value}})}/></label><div className="two"><label>Factuurnummer<input value={form.data.invoice_number} onChange={e=>setForm({...form,data:{...form.data,invoice_number:e.target.value}})}/></label><label>Factuurdatum<input type="date" value={form.data.invoice_date} onChange={e=>setForm({...form,data:{...form.data,invoice_date:e.target.value}})}/></label></div><label>Omschrijving<textarea value={form.data.description} onChange={e=>setForm({...form,data:{...form.data,description:e.target.value}})}/></label><label>Kostenrekening<select value={form.data.ledger_account_id} onChange={e=>setForm({...form,data:{...form.data,ledger_account_id:e.target.value}})}><option value="">Overige bedrijfskosten</option>{data.accounts.filter((a:any)=>a.type==='kosten').map((a:any)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><div className="three"><label>Excl. BTW<input type="number" step="0.01" value={form.data.subtotal} onChange={e=>{const subtotal=Number(e.target.value),vat=Number(form.data.vat_total);setForm({...form,data:{...form.data,subtotal,total:subtotal+vat}})}}/></label><label>BTW<input type="number" step="0.01" value={form.data.vat_total} onChange={e=>{const vat=Number(e.target.value),subtotal=Number(form.data.subtotal);setForm({...form,data:{...form.data,vat_total:vat,total:subtotal+vat}})}}/></label><label>Totaal<input type="number" step="0.01" value={form.data.total} onChange={e=>setForm({...form,data:{...form.data,total:Number(e.target.value)}})}/></label></div></>}
 {form.kind==='account'&&<><div className="two"><label>Code<input value={form.data.code} onChange={e=>setForm({...form,data:{...form.data,code:e.target.value}})}/></label><label>Naam<input value={form.data.name} onChange={e=>setForm({...form,data:{...form.data,name:e.target.value}})}/></label></div><label>Type<select value={form.data.type} onChange={e=>setForm({...form,data:{...form.data,type:e.target.value}})}><option value="activa">Activa</option><option value="passiva">Passiva</option><option value="kosten">Kosten</option><option value="opbrengsten">Opbrengsten</option></select></label></>}
 {form.kind==='journal'&&<><div className="two"><label>Datum<input type="date" value={form.data.entry_date} onChange={e=>setForm({...form,data:{...form.data,entry_date:e.target.value}})}/></label><label>Referentie<input value={form.data.reference} onChange={e=>setForm({...form,data:{...form.data,reference:e.target.value}})}/></label></div><label>Omschrijving<input value={form.data.description} onChange={e=>setForm({...form,data:{...form.data,description:e.target.value}})}/></label>{form.data.lines.map((l:any,i:number)=><div className="journalLine" key={i}><select value={l.ledger_account_id} onChange={e=>{const lines=[...form.data.lines];lines[i]={...l,ledger_account_id:e.target.value};setForm({...form,data:{...form.data,lines}})}}><option value="">Rekening</option>{data.accounts.map((a:any)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select><input placeholder="Debet" type="number" step="0.01" value={l.debit} onChange={e=>{const lines=[...form.data.lines];lines[i]={...l,debit:Number(e.target.value)};setForm({...form,data:{...form.data,lines}})}}/><input placeholder="Credit" type="number" step="0.01" value={l.credit} onChange={e=>{const lines=[...form.data.lines];lines[i]={...l,credit:Number(e.target.value)};setForm({...form,data:{...form.data,lines}})}}/></div>)}<button className="secondary" onClick={()=>setForm({...form,data:{...form.data,lines:[...form.data.lines,{ledger_account_id:'',description:'',debit:0,credit:0}]}})}>+ Regel</button></>}
 <div className="actions modalActions"><button className="secondary" onClick={()=>setForm(null)}>Annuleren</button><button onClick={save}>Opslaan</button></div></div></div>}
 <style jsx>{`*{box-sizing:border-box}.wrap{max-width:1500px;margin:auto;padding:28px;background:#f4f6f8;min-height:100vh;color:#172033}header{display:flex;justify-content:space-between;gap:20px;align-items:center}h1{font-size:36px;margin:4px 0}h2{margin-top:0}header p,small{color:#667085}.actions,.tabs,.quick{display:flex;gap:9px;flex-wrap:wrap}.actions a,.actions button,button{border:0;border-radius:10px;padding:10px 14px;background:#172033;color:#fff;text-decoration:none;font-weight:700;cursor:pointer}.actions select{width:auto}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:20px 0}.stat,.card{background:#fff;border:1px solid #e4e7ec;border-radius:16px;padding:18px;box-shadow:0 8px 24px #1018280a}.stat{display:grid;gap:5px}.stat b{font-size:23px}.tabs{margin-bottom:12px}.tabs button{background:#e8ebf0;color:#344054}.tabs .active{background:#172033;color:#fff}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.wide{grid-column:1/-1}.metric{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #eee}.metric.total{font-size:20px}.cardHead{display:flex;justify-content:space-between;align-items:center;gap:15px}.table{overflow:auto}.tr{display:grid;gap:10px;padding:12px;border-bottom:1px solid #eee;align-items:center}.tr.account{grid-template-columns:.6fr 1.7fr 1fr 1fr 1fr 1fr;min-width:850px}.tr.entry{grid-template-columns:.8fr 2fr 1fr .7fr 1fr 1fr;min-width:850px}.tr.purchase{grid-template-columns:.8fr 1.4fr 1fr 1.5fr .8fr .8fr .8fr .7fr .8fr;min-width:1250px}.tr.vat{grid-template-columns:.6fr 1.6fr 1fr 1fr 1fr;min-width:750px}.head{font-size:12px;font-weight:800;color:#667085}.badge{padding:5px 8px;border-radius:99px;background:#f2f4f7;font-style:normal}.badge.betaald{background:#dcfce7}.error{background:#fee4e2;color:#912018;padding:12px;border-radius:10px;margin:14px 0}.overlay{position:fixed;inset:0;background:#0008;display:grid;place-items:center;z-index:50;padding:20px}.modal{background:#fff;border-radius:16px;padding:22px;width:min(760px,100%);max-height:92vh;overflow:auto}.modal label{display:grid;gap:6px;margin:12px 0}.two,.three{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.three{grid-template-columns:repeat(3,1fr)}input,select,textarea{width:100%;border:1px solid #d0d5dd;border-radius:9px;padding:10px;font:inherit}.journalLine{display:grid;grid-template-columns:2fr 1fr 1fr;gap:8px;margin:8px 0}.secondary{background:#e5e7eb!important;color:#111827!important}.modalActions{justify-content:flex-end;margin-top:18px}button:disabled{opacity:.5;cursor:wait}@media(max-width:900px){header{align-items:flex-start;flex-direction:column}.stats{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}.two,.three{grid-template-columns:1fr}.journalLine{grid-template-columns:1fr}}`}</style>
 </main>
}
function Stat({label,value}:{label:string,value:string}){return <article className="stat"><small>{label}</small><b>{value}</b></article>}
function EntryTable({entries}:{entries:any[]}){return <div className="table"><div className="tr entry head"><span>Datum</span><span>Omschrijving</span><span>Referentie</span><span>Regels</span><span>Debet</span><span>Credit</span></div>{entries.map(e=><div className="tr entry" key={e.id}><span>{String(e.entry_date).slice(0,10)}</span><span><b>{e.description}</b></span><span>{e.reference||'–'}</span><span>{e.line_count}</span><span>{euro(e.debit)}</span><span>{euro(e.credit)}</span></div>)}</div>}
