import {NextResponse} from 'next/server';
import pool from '@/lib/db';
import {can,readSession} from '@/lib/auth';

let ready=false;
async function ensureSchema(){
 if(ready)return;
 await pool.query(`CREATE TABLE IF NOT EXISTS crm_contacts (id INT AUTO_INCREMENT PRIMARY KEY,customer_id INT NOT NULL,first_name VARCHAR(100) NOT NULL,last_name VARCHAR(100) NULL,role VARCHAR(120) NULL,email VARCHAR(190) NULL,phone VARCHAR(60) NULL,mobile VARCHAR(60) NULL,is_primary TINYINT(1) NOT NULL DEFAULT 0,notes TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_crm_contact_customer(customer_id),INDEX idx_crm_contact_email(email)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
 await pool.query(`CREATE TABLE IF NOT EXISTS crm_notes (id INT AUTO_INCREMENT PRIMARY KEY,customer_id INT NOT NULL,contact_id INT NULL,title VARCHAR(190) NULL,content TEXT NOT NULL,created_by VARCHAR(190) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_crm_note_customer(customer_id),INDEX idx_crm_note_contact(contact_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
 await pool.query(`CREATE TABLE IF NOT EXISTS crm_tasks (id INT AUTO_INCREMENT PRIMARY KEY,customer_id INT NULL,contact_id INT NULL,title VARCHAR(190) NOT NULL,description TEXT NULL,due_date DATE NULL,priority VARCHAR(20) NOT NULL DEFAULT 'normaal',status VARCHAR(30) NOT NULL DEFAULT 'open',assigned_to VARCHAR(190) NULL,completed_at DATETIME NULL,created_by VARCHAR(190) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_crm_task_customer(customer_id),INDEX idx_crm_task_due(due_date),INDEX idx_crm_task_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
 await pool.query(`CREATE TABLE IF NOT EXISTS crm_activities (id INT AUTO_INCREMENT PRIMARY KEY,customer_id INT NOT NULL,contact_id INT NULL,activity_type VARCHAR(40) NOT NULL DEFAULT 'notitie',subject VARCHAR(190) NOT NULL,description TEXT NULL,activity_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,created_by VARCHAR(190) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX idx_crm_activity_customer(customer_id),INDEX idx_crm_activity_date(activity_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
 await pool.query(`CREATE TABLE IF NOT EXISTS crm_files (id INT AUTO_INCREMENT PRIMARY KEY,customer_id INT NOT NULL,contact_id INT NULL,file_name VARCHAR(255) NOT NULL,file_url TEXT NOT NULL,mime_type VARCHAR(120) NULL,description VARCHAR(255) NULL,uploaded_by VARCHAR(190) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX idx_crm_file_customer(customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
 ready=true;
}
async function auth(permission:string){const s=await readSession();return can(s,permission)?s:null}
const actor=(s:any)=>s?.name||s?.email||'gebruiker';

export async function GET(req:Request){
 const s=await auth('data.read');if(!s)return NextResponse.json({error:'Geen toegang'},{status:403});await ensureSchema();
 const url=new URL(req.url),customerId=Number(url.searchParams.get('customer_id')||0),args=customerId?[customerId]:[];
 const [[customers],[contacts],[notes],[tasks],[activities],[files],[revenue]]:any=await Promise.all([
  pool.query(`SELECT c.*,(SELECT COUNT(*) FROM crm_contacts x WHERE x.customer_id=c.id) contact_count,(SELECT COUNT(*) FROM crm_tasks x WHERE x.customer_id=c.id AND x.status<>'gereed') open_task_count,(SELECT MAX(x.activity_at) FROM crm_activities x WHERE x.customer_id=c.id) last_activity FROM customers c ${customerId?'WHERE c.id=?':''} ORDER BY c.name`,args),
  pool.query(`SELECT x.*,c.name customer_name FROM crm_contacts x LEFT JOIN customers c ON c.id=x.customer_id ${customerId?'WHERE x.customer_id=?':''} ORDER BY x.is_primary DESC,x.first_name`,args),
  pool.query(`SELECT x.*,c.name customer_name,CONCAT_WS(' ',p.first_name,p.last_name) contact_name FROM crm_notes x LEFT JOIN customers c ON c.id=x.customer_id LEFT JOIN crm_contacts p ON p.id=x.contact_id ${customerId?'WHERE x.customer_id=?':''} ORDER BY x.created_at DESC LIMIT 500`,args),
  pool.query(`SELECT x.*,c.name customer_name,CONCAT_WS(' ',p.first_name,p.last_name) contact_name FROM crm_tasks x LEFT JOIN customers c ON c.id=x.customer_id LEFT JOIN crm_contacts p ON p.id=x.contact_id ${customerId?'WHERE x.customer_id=?':''} ORDER BY (x.status='gereed'),x.due_date IS NULL,x.due_date,x.id DESC LIMIT 500`,args),
  pool.query(`SELECT x.*,c.name customer_name,CONCAT_WS(' ',p.first_name,p.last_name) contact_name FROM crm_activities x LEFT JOIN customers c ON c.id=x.customer_id LEFT JOIN crm_contacts p ON p.id=x.contact_id ${customerId?'WHERE x.customer_id=?':''} ORDER BY x.activity_at DESC LIMIT 500`,args),
  pool.query(`SELECT x.*,c.name customer_name FROM crm_files x LEFT JOIN customers c ON c.id=x.customer_id ${customerId?'WHERE x.customer_id=?':''} ORDER BY x.created_at DESC LIMIT 500`,args),
  pool.query(`SELECT customer_id,COUNT(*) document_count,SUM(CASE WHEN type='factuur' AND status='betaald' THEN total ELSE 0 END) revenue,SUM(CASE WHEN type='factuur' AND status NOT IN ('betaald','geannuleerd') THEN total ELSE 0 END) outstanding FROM documents GROUP BY customer_id`)
 ]);
 const rm=Object.fromEntries(revenue.map((x:any)=>[Number(x.customer_id),x])),enriched=customers.map((x:any)=>({...x,...(rm[Number(x.id)]||{document_count:0,revenue:0,outstanding:0})})),today=new Date().toISOString().slice(0,10);
 return NextResponse.json({customers:enriched,contacts,notes,tasks,activities,files,kpis:{customers:enriched.length,prospects:enriched.filter((x:any)=>x.status==='prospect').length,openTasks:tasks.filter((x:any)=>x.status!=='gereed').length,overdueTasks:tasks.filter((x:any)=>x.status!=='gereed'&&x.due_date&&String(x.due_date).slice(0,10)<today).length,revenue:enriched.reduce((a:number,x:any)=>a+Number(x.revenue||0),0),outstanding:enriched.reduce((a:number,x:any)=>a+Number(x.outstanding||0),0)}});
}

export async function POST(req:Request){
 const s:any=await auth('data.write');if(!s)return NextResponse.json({error:'Geen toegang'},{status:403});await ensureSchema();const b=await req.json(),d=b.data||{},by=actor(s);
 if(b.action==='contact'){if(!d.customer_id||!d.first_name)return NextResponse.json({error:'Klant en voornaam zijn verplicht'},{status:400});if(d.is_primary)await pool.query('UPDATE crm_contacts SET is_primary=0 WHERE customer_id=?',[d.customer_id]);const [r]:any=await pool.query('INSERT INTO crm_contacts (customer_id,first_name,last_name,role,email,phone,mobile,is_primary,notes) VALUES (?,?,?,?,?,?,?,?,?)',[d.customer_id,d.first_name,d.last_name||null,d.role||null,d.email||null,d.phone||null,d.mobile||null,d.is_primary?1:0,d.notes||null]);await pool.query('INSERT INTO crm_activities (customer_id,contact_id,activity_type,subject,created_by) VALUES (?,?,?,?,?)',[d.customer_id,r.insertId,'contact','Contactpersoon toegevoegd',by]);return NextResponse.json({id:r.insertId});}
 if(b.action==='note'){if(!d.customer_id||!d.content)return NextResponse.json({error:'Klant en notitie zijn verplicht'},{status:400});const [r]:any=await pool.query('INSERT INTO crm_notes (customer_id,contact_id,title,content,created_by) VALUES (?,?,?,?,?)',[d.customer_id,d.contact_id||null,d.title||null,d.content,by]);await pool.query('INSERT INTO crm_activities (customer_id,contact_id,activity_type,subject,description,created_by) VALUES (?,?,?,?,?,?)',[d.customer_id,d.contact_id||null,'notitie',d.title||'Notitie toegevoegd',d.content,by]);return NextResponse.json({id:r.insertId});}
 if(b.action==='task'){if(!d.title)return NextResponse.json({error:'Taaknaam is verplicht'},{status:400});const [r]:any=await pool.query('INSERT INTO crm_tasks (customer_id,contact_id,title,description,due_date,priority,status,assigned_to,created_by) VALUES (?,?,?,?,?,?,?,?,?)',[d.customer_id||null,d.contact_id||null,d.title,d.description||null,d.due_date||null,d.priority||'normaal',d.status||'open',d.assigned_to||null,by]);if(d.customer_id)await pool.query('INSERT INTO crm_activities (customer_id,contact_id,activity_type,subject,description,created_by) VALUES (?,?,?,?,?,?)',[d.customer_id,d.contact_id||null,'taak',`Taak: ${d.title}`,d.description||null,by]);return NextResponse.json({id:r.insertId});}
 if(b.action==='activity'){if(!d.customer_id||!d.subject)return NextResponse.json({error:'Klant en onderwerp zijn verplicht'},{status:400});const [r]:any=await pool.query('INSERT INTO crm_activities (customer_id,contact_id,activity_type,subject,description,activity_at,created_by) VALUES (?,?,?,?,?,?,?)',[d.customer_id,d.contact_id||null,d.activity_type||'contact',d.subject,d.description||null,d.activity_at||new Date(),by]);return NextResponse.json({id:r.insertId});}
 if(b.action==='file'){if(!d.customer_id||!d.file_name||!d.file_url)return NextResponse.json({error:'Klant, bestandsnaam en URL zijn verplicht'},{status:400});const [r]:any=await pool.query('INSERT INTO crm_files (customer_id,contact_id,file_name,file_url,mime_type,description,uploaded_by) VALUES (?,?,?,?,?,?,?)',[d.customer_id,d.contact_id||null,d.file_name,d.file_url,d.mime_type||null,d.description||null,by]);await pool.query('INSERT INTO crm_activities (customer_id,contact_id,activity_type,subject,description,created_by) VALUES (?,?,?,?,?,?)',[d.customer_id,d.contact_id||null,'bestand',`Bestand toegevoegd: ${d.file_name}`,d.description||null,by]);return NextResponse.json({id:r.insertId});}
 return NextResponse.json({error:'Ongeldige actie'},{status:400});
}

export async function PUT(req:Request){
 const s=await auth('data.write');if(!s)return NextResponse.json({error:'Geen toegang'},{status:403});await ensureSchema();const b=await req.json(),d=b.data||{},id=Number(d.id);if(!id)return NextResponse.json({error:'ID ontbreekt'},{status:400});
 if(b.action==='task'){const allowed=['customer_id','contact_id','title','description','due_date','priority','status','assigned_to','completed_at'],keys=allowed.filter(k=>Object.prototype.hasOwnProperty.call(d,k));if(d.status==='gereed'&&!keys.includes('completed_at')){keys.push('completed_at');d.completed_at=new Date()}if(!keys.length)return NextResponse.json({ok:true});await pool.query(`UPDATE crm_tasks SET ${keys.map(k=>'`'+k+'`=?').join(',')} WHERE id=?`,[...keys.map(k=>d[k]??null),id]);return NextResponse.json({ok:true});}
 if(b.action==='contact'){if(d.is_primary&&d.customer_id)await pool.query('UPDATE crm_contacts SET is_primary=0 WHERE customer_id=?',[d.customer_id]);const allowed=['customer_id','first_name','last_name','role','email','phone','mobile','is_primary','notes'],keys=allowed.filter(k=>Object.prototype.hasOwnProperty.call(d,k));if(!keys.length)return NextResponse.json({ok:true});await pool.query(`UPDATE crm_contacts SET ${keys.map(k=>'`'+k+'`=?').join(',')} WHERE id=?`,[...keys.map(k=>d[k]??null),id]);return NextResponse.json({ok:true});}
 return NextResponse.json({error:'Ongeldige actie'},{status:400});
}

export async function DELETE(req:Request){
 const s=await auth('data.write');if(!s)return NextResponse.json({error:'Geen toegang'},{status:403});await ensureSchema();const b=await req.json(),id=Number(b.id),tables:any={contact:'crm_contacts',note:'crm_notes',task:'crm_tasks',activity:'crm_activities',file:'crm_files'},table=tables[b.action];if(!table||!id)return NextResponse.json({error:'Ongeldige verwijderactie'},{status:400});await pool.query(`DELETE FROM ${table} WHERE id=?`,[id]);return NextResponse.json({ok:true});
}
