'use client';
import {useEffect,useMemo,useState} from 'react';

const money=(v:any)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(v||0));
const customer=(d:any)=>d.company_name||d.customer_name||d.name||'Onbekend';

export default function EmailCenter(){
 const [docs,setDocs]=useState<any[]>([]),[logs,setLogs]=useState<any[]>([]),[query,setQuery]=useState(''),[selected,setSelected]=useState<any>(null),[form,setForm]=useState({recipient:'',subject:'',message:''}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false);
 async function load(){setLoading(true);const [a,b]=await Promise.all([fetch('/api/facturatie',{cache:'no-store'}),fetch('/api/facturatie/email',{cache:'no-store'})]);const [j,k]=await Promise.all([a.json(),b.json()]);setLoading(false);if(!a.ok||!b.ok){setError(j.error||k.error||'Laden mislukt');return}setDocs((j.documents||[]).filter((d:any)=>['offerte','factuur'].includes(d.type)));setLogs(k.logs||[]);}
 useEffect(()=>{load()},[]);
 const rows=useMemo(()=>docs.filter(d=>JSON.stringify(d).toLowerCase().includes(query.toLowerCase())),[docs,query]);
 function open(d:any){setSelected(d);setForm({recipient:d.customer_email||'',subject:`${d.type==='offerte'?'Offerte':'Factuur'} ${d.number} van KlusHulp Noord`,message:d.type==='offerte'?'Wij hebben een offerte voor u klaargezet. Via de knop in de e-mail kunt u deze bekijken en direct accepteren of afwijzen.':'Uw factuur staat voor u klaar. Via de knop in de e-mail kunt u deze bekijken en, indien beschikbaar, direct betalen.'});setError('');setNotice('');}
 async function send(){if(!selected)return;setSending(true);setError('');setNotice('');const r=await fetch('/api/facturatie/email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document_id:selected.id,...form})}),j=await r.json();setSending(false);if(!r.ok){setError(j.error||'Versturen mislukt');return}setNotice(`E-mail is verstuurd naar ${j.recipient}.`);setSelected(null);await load();}
 return <main className="wrap"><header><div><small>KlusHulp Noord ERP v8.3</small><h1>E-mailcentrum</h1><p>Verstuur offertes en facturen met een veilige klantportaal-link.</p></div><div className="actions"><a href="/facturatie">← Facturatie</a><a href="/">Administratie</a></div></header>
 {error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}
 <section className="grid"><article className="card"><div className="toolbar"><h2>Documenten</h2><input placeholder="Zoeken..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{loading?<p>Laden…</p>:<div className="table"><div className="tr head"><span>Nummer</span><span>Klant</span><span>Type</span><span>Totaal</span><span>E-mail</span><span></span></div>{rows.map(d=><div className="tr" key={d.id}><b>{d.number}</b><span>{customer(d)}</span><span>{d.type}</span><span>{money(d.total)}</span><span>{d.customer_email||<em>Ontbreekt</em>}</span><button onClick={()=>open(d)}>E-mail</button></div>)}</div>}</article>
 <article className="card"><h2>Verzendgeschiedenis</h2><div className="history">{logs.length===0?<p>Nog geen e-mails verzonden.</p>:logs.map(l=><div className="log" key={l.id}><div><b>{l.document_number}</b> · {l.recipient}</div><small>{String(l.sent_at||'').replace('T',' ').slice(0,16)} · {l.status}</small>{l.error_message&&<p>{l.error_message}</p>}</div>)}</div></article></section>
 {selected&&<div className="overlay"><div className="modal"><h2>{selected.type==='offerte'?'Offerte':'Factuur'} versturen</h2><p><b>{selected.number}</b> · {customer(selected)} · {money(selected.total)}</p><label>Ontvanger<input type="email" value={form.recipient} onChange={e=>setForm({...form,recipient:e.target.value})}/></label><label>Onderwerp<input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Bericht<textarea rows={6} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><div className="tip">De e-mail bevat automatisch een beveiligde klantlink die 30 dagen geldig is.</div><div className="actions"><button className="secondary" onClick={()=>setSelected(null)}>Annuleren</button><button disabled={sending} onClick={send}>{sending?'Versturen…':'E-mail versturen'}</button></div></div></div>}
 <style jsx>{`*{box-sizing:border-box}.wrap{min-height:100vh;background:#f4f6f8;color:#18212f;padding:28px;max-width:1500px;margin:auto}header{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:20px}h1{font-size:36px;margin:4px 0}h2{margin:0 0 14px}small,header p{color:#667085}.actions{display:flex;gap:9px;flex-wrap:wrap}.actions a,.actions button,button{border:0;border-radius:10px;padding:10px 14px;background:#172033;color:#fff;text-decoration:none;font-weight:700;cursor:pointer}.grid{display:grid;grid-template-columns:2fr 1fr;gap:16px}.card{background:#fff;border:1px solid #e4e7ec;border-radius:16px;padding:18px;box-shadow:0 8px 24px #1018280a}.toolbar{display:flex;justify-content:space-between;gap:12px;align-items:center}.toolbar input{max-width:360px}.table{overflow:auto}.tr{display:grid;grid-template-columns:1fr 1.4fr .7fr .8fr 1.5fr .6fr;gap:10px;padding:12px;border-bottom:1px solid #eee;align-items:center;min-width:900px}.head{font-size:12px;color:#667085;font-weight:800}.tr button{padding:7px 10px;background:#7c3aed}.history{max-height:650px;overflow:auto}.log{padding:12px 0;border-bottom:1px solid #eee}.log p{color:#b42318;margin:5px 0 0}.error,.notice{padding:12px;border-radius:10px;margin:12px 0}.error{background:#fee4e2;color:#912018}.notice{background:#dcfce7;color:#166534}.overlay{position:fixed;inset:0;background:#0008;display:grid;place-items:center;z-index:50;padding:20px}.modal{background:#fff;border-radius:16px;padding:22px;width:min(650px,100%);max-height:90vh;overflow:auto}.modal label{display:grid;gap:6px;margin:12px 0}input,textarea{width:100%;border:1px solid #d0d5dd;border-radius:9px;padding:10px;font:inherit}.tip{background:#f5f3ff;color:#5b21b6;padding:11px;border-radius:9px;margin:12px 0}.secondary{background:#e5e7eb!important;color:#111827!important}button:disabled{opacity:.55;cursor:wait}@media(max-width:950px){.grid{grid-template-columns:1fr}header{align-items:flex-start;flex-direction:column}.toolbar{align-items:flex-start;flex-direction:column}.toolbar input{max-width:none}}`}</style></main>;
}
